<!DOCTYPE html>
<html>
  <head>
  	<script src="<?php echo WEB_PATH;?>/public/assets/javascripts/jquery/jquery.min.js" type="text/javascript"></script>
    <title>Playboyviet</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <meta content='text/html;charset=utf-8' http-equiv='content-type'>
    <meta content='Flat administration template for Twitter Bootstrap. Twitter Bootstrap 3 template with Ruby on Rails support.' name='description'>
    <link href='<?php echo WEB_PATH;?>/public/assets/images/maybanhang.ico' rel='shortcut icon' type='image/x-icon'>
    <link href='<?php echo WEB_PATH;?>/public/assets/images/meta_icons/apple-touch-icon.png' rel='apple-touch-icon-precomposed'>
    <link href='<?php echo WEB_PATH;?>/public/assets/images/meta_icons/apple-touch-icon-57x57.png' rel='apple-touch-icon-precomposed' sizes='57x57'>
    <link href='<?php echo WEB_PATH;?>/public/assets/images/meta_icons/apple-touch-icon-72x72.png' rel='apple-touch-icon-precomposed' sizes='72x72'>
    <link href='<?php echo WEB_PATH;?>/public/assets/images/meta_icons/apple-touch-icon-114x114.png' rel='apple-touch-icon-precomposed' sizes='114x114'>
    <link href='<?php echo WEB_PATH;?>/public/assets/images/meta_icons/apple-touch-icon-144x144.png' rel='apple-touch-icon-precomposed' sizes='144x144'>
    <!-- / bootstrap [required] -->
    <link href="<?php echo WEB_PATH;?>/public/assets/stylesheets/bootstrap/bootstrap.css" media="all" rel="stylesheet" type="text/css" />
    <!-- / theme file [required] -->
    <link href="<?php echo WEB_PATH;?>/public/assets/stylesheets/light-theme.css" media="all" id="color-settings-body-color" rel="stylesheet" type="text/css" />
    <link href="<?php echo WEB_PATH;?>/public/assets/stylesheets/view-custom.css" rel="stylesheet" type="text/css" />
    
    
     <!-- / START - page related stylesheets [optional] -->
    <link href="<?php echo WEB_PATH;?>/public/assets/stylesheets/plugins/bootstrap_daterangepicker/bootstrap-daterangepicker.css" media="all" rel="stylesheet" type="text/css" />
    <link href="<?php echo WEB_PATH;?>/public/assets/stylesheets/plugins/fullcalendar/fullcalendar.css" media="all" rel="stylesheet" type="text/css" />
    <link href="<?php echo WEB_PATH;?>/public/assets/stylesheets/plugins/common/bootstrap-wysihtml5.css" media="all" rel="stylesheet" type="text/css" />
    <!-- / END - page related stylesheets [optional] -->
   
    <!-- / coloring file [optional] (if you are going to use custom contrast color) -->
    <link href="<?php echo WEB_PATH;?>/public/assets/stylesheets/theme-colors.css" media="all" rel="stylesheet" type="text/css" />
    <!-- / demo file [not required!] -->
    <link href="<?php echo WEB_PATH;?>/public/assets/stylesheets/demo.css" media="all" rel="stylesheet" type="text/css" />
    <!--[if lt IE 9]>
      <script src="<?php echo WEB_PATH;?>/public/assets/javascripts/ie/html5shiv.js" type="text/javascript"></script>
      <script src="<?php echo WEB_PATH;?>/public/assets/javascripts/ie/respond.min.js" type="text/javascript"></script>
    <![endif]-->
    
    <style type="text/css">
    .box_message{
position: fixed;
height: 0px;
top: 0px;
left: 0px;
width: 100%;
z-index: 999999999;
}
.alert{
text-align: center !important;
/* background-color: #49BF67 !important*/
}
</style>
    

   <!-- timeline -->
<link rel="stylesheet" href="<?php echo WEB_PATH;?>/public/css/animate.css">
<link rel="stylesheet" href="<?php echo WEB_PATH;?>/public/css/styletimeline.css">
<script type="text/javascript" src="<?php echo WEB_PATH;?>/public/js/jquery.linkify.min.js"></script>
<script type="text/javascript" src="<?php echo WEB_PATH;?>/public/js/jquery.livequery.js"></script>
<script type="text/javascript" src="<?php echo WEB_PATH;?>/public/js/timlineprosees.js"></script>

    
    
    
  </head>
  <body class='contrast-blue '>
    <?php include_once APPLICATION_PATH.'/layouts/flatty/header.phtml';?>
    <div id='wrapper'>
      <div id='main-nav-bg'></div>
      <?php include_once APPLICATION_PATH.'/layouts/flatty/sidebar.phtml';?>
      <section id='content'>
        <div class='container'>
          <?php echo $this->layout()->content ?>    
          <?php include_once APPLICATION_PATH.'/layouts/flatty/footer.phtml';?>
        </div>
      </section>
    </div>
 
    
    
    
     <!-- / jquery [required] -->
    <script src="<?php echo WEB_PATH;?>/public/assets/javascripts/jquery/jquery.min.js" type="text/javascript"></script>
    <!-- / jquery mobile (for touch events) -->
    <script src="<?php echo WEB_PATH;?>/public/assets/javascripts/jquery/jquery.mobile.custom.min.js" type="text/javascript"></script>
    <!-- / jquery migrate (for compatibility with new jquery) [required] -->
    <script src="<?php echo WEB_PATH;?>/public/assets/javascripts/jquery/jquery-migrate.min.js" type="text/javascript"></script>
    <!-- / jquery ui -->
    <script src="<?php echo WEB_PATH;?>/public/assets/javascripts/jquery/jquery-ui.min.js" type="text/javascript"></script>
    <!-- / jQuery UI Touch Punch -->
    <script src="<?php echo WEB_PATH;?>/public/assets/javascripts/plugins/jquery_ui_touch_punch/jquery.ui.touch-punch.min.js" type="text/javascript"></script>
    <!-- / bootstrap [required] -->
    <script src="<?php echo WEB_PATH;?>/public/assets/javascripts/bootstrap/bootstrap.js" type="text/javascript"></script>
    <!-- / modernizr -->
    <script src="<?php echo WEB_PATH;?>/public/assets/javascripts/plugins/modernizr/modernizr.min.js" type="text/javascript"></script>
    <!-- / retina -->
    <script src="<?php echo WEB_PATH;?>/public/assets/javascripts/plugins/retina/retina.js" type="text/javascript"></script>
    <!-- / theme file [required] -->
    <script src="<?php echo WEB_PATH;?>/public/assets/javascripts/theme.js" type="text/javascript"></script>
    <!-- / demo file [not required!] -->
    <script src="<?php echo WEB_PATH;?>/public/assets/javascripts/demo.js" type="text/javascript"></script>

    <!-- / START - page related files and scripts [optional] -->
   
    <script src="<?php echo WEB_PATH;?>/public/assets/javascripts/plugins/flot/excanvas.js" type="text/javascript"></script>
    <script src="<?php echo WEB_PATH;?>/public/assets/javascripts/plugins/flot/flot.min.js" type="text/javascript"></script>
    <script src="<?php echo WEB_PATH;?>/public/assets/javascripts/plugins/flot/flot.resize.js" type="text/javascript"></script>
   
  
    <script src="<?php echo WEB_PATH;?>/public/assets/javascripts/plugins/bootstrap_daterangepicker/bootstrap-daterangepicker.js" type="text/javascript"></script>
    <script src="<?php echo WEB_PATH;?>/public/assets/javascripts/plugins/common/moment.min.js" type="text/javascript"></script>
    <script src="<?php echo WEB_PATH;?>/public/assets/javascripts/plugins/bootbox/bootbox.min.js" type="text/javascript"></script>
    <script src="<?php echo WEB_PATH;?>/public/assets/javascripts/plugins/slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <script src="<?php echo WEB_PATH;?>/public/assets/javascripts/plugins/timeago/jquery.timeago.js" type="text/javascript"></script>
    <script src="<?php echo WEB_PATH;?>/public/assets/javascripts/plugins/common/wysihtml5.min.js" type="text/javascript"></script>
    <script src="<?php echo WEB_PATH;?>/public/assets/javascripts/plugins/common/bootstrap-wysihtml5.js" type="text/javascript"></script>
    <script src="<?php echo WEB_PATH;?>/public/assets/javascripts/plugins/fullcalendar/fullcalendar.min.js" type="text/javascript"></script>
    <script src="<?php echo WEB_PATH;?>/public/assets/javascripts/plugins/bootbox/bootbox.min.js" type="text/javascript"></script>
    <script src="<?php echo WEB_PATH;?>/public/assets/javascripts/plugins/validate/jquery.validate.min.js" type="text/javascript"></script>
    <script src="<?php echo WEB_PATH;?>/public/assets/javascripts/plugins/validate/additional-methods.js" type="text/javascript"></script>
    
  
  
    <?php echo $this->inlineScript();?>
    <link href="<?php echo WEB_PATH;?>/public/assets/stylesheets/custom.css" media="all" id="color-settings-body-color" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="<?php echo WEB_PATH;?>/public/front/js/process.js"></script> 
    

   
  </body>
</html>