<?php 
	$appsatellite = $this->appsatellite;
	$status	  = $this->status;
	$message  = null;
	if($status == 1){
		$message = '<div class="ub_message">Dữ liệu đã được cập nhật thành công</div>';
	}elseif($status == "-1"){
		$message = '<div class="ub_message"><span>appsatellite key bị trùng, vui lòng chọn key khác!</span></div>';
	}
	$active = (int)@$appsatellite['active'];
?>
<div class='row' id='content-wrapper'>
            <div class='col-xs-12'>
              <div class='row'>
                <div class='col-sm-12'>
                  <div class='page-header'>
                    <h1 class='pull-left'>
                      <i class='icon-edit'></i>
                      <span class="page_title">Thêm mới / Cập nhật </span>
                    </h1>
                  </div>
                </div>
              </div>
              <div class='row'>
                <div class='col-sm-12'>
                  <div class='box'>
                    <div class='box-header blue-background'>
                      <div class='title'>
                        <div class='icon-edit'></div>
                        Nhóm tin
                      </div>
                      <div class='actions'>
                        <a class="btn box-remove btn-xs btn-link" href="#"><i class='icon-remove'></i>
                        </a>
                        <a class="btn box-collapse btn-xs btn-link" href="#"><i></i>
                        </a>
                      </div>
                    </div>
                    <div class='box-content'>
                        <form id="frmUpdate" name="frmUpdate" class="form form-horizontal" style="margin-bottom: 0;" method="post" action="<?php echo WEB_PATH;?>/administrator/appsatellite/update" accept-charset="UTF-8" enctype="multipart/form-data" accept-charset="UTF-8" >
						<input type="hidden" id="id" name="id" value="<?php echo $this->id;?>">
						<input type="hidden" id="do" name="do" value="submit" />
                        <input name="authenticity_token" type="hidden" />
                         <div class='form-group'>
                         <label class='col-md-3 control-label' for='contentdetailfull_key'>Title - NameApp</label>
		                        <div class='col-md-5'>
		                        	<?php echo $this->contentdetailfullGroup; 
		                        	       //var_dump($this->contentdetailfullGroup);
		                        	       //print_r($this->contentdetailfullGroup);
		                        	       ?>
		                        </div>
                        </div>
                      <?php 
                      $http   = 'http';
                      ?>
                     
		                  <?php if ( (strpos($appsatellite['image_thumbnail'],$http )=== false) and ($appsatellite['image_thumbnail'] != "")) {?>
		                      <div class='form-group'>
		                        <label class='col-md-3 control-label' for='thumbnail'>ThumbNail</label>
		                        <div class='col-md-5'>
		                           <img type="text" class='form-control' id="thumbnail" name="thumbnail" placeholder='Images' src="<?php echo WEB_PATH;?>/public/uploads/news/<?php echo @$appsatellite['image_thumbnail'];?>" style="width: 400px;height:400px;" />
		                        </div>
		                      </div>
		                  <?php }?>
		                  
		                     <?php if ((strpos($appsatellite['image_thumbnail'],$http )=== 0 ) and ($appsatellite['image_thumbnail'] != "")) {?>
		                      <div class='form-group'>
		                        <label class='col-md-3 control-label' for='thumbnail'>ThumbNail</label>
		                        <div class='col-md-5'>
		                           <img type="text" class='form-control' id="thumbnail" name="thumbnail" placeholder='Images' src="<?php echo @$appsatellite['image_thumbnail'];?>" style="width: 400px;height:400px;" />
		                        </div>
		                      </div>
		                  <?php }?>
		                   
		                      <?php if($this->image){?>
		                        <div class='form-group'>
		                          <label class='control-label col-sm-3' for='Thứ tự sắp xếp ưu tiên'>Ảnh đang dùng</label>
		                          <div class='col-sm-4 controls'>
		                            <img width="340" height="230" alt="<?php echo @$appsatellite['image_thumbnail'];?>" src="<?php echo WEB_PATH;?>/public/uploads/news/<?php echo $image;?>" />
					              <input type="checkbox" name="delete_image"> Xóa ảnh 
		                           </div>
		                        </div>
		                        <?php }?>
		                        
		                      <div class='form-group'>
		                        <label class='col-md-3 control-label' for='srcimgaes'>Images</label>
		                        <div class='col-md-5'>
		                        	<input class='form-control' id='srcimgaes' name='srcimgaes' type="file" />
		                        </div>
		                      </div>
                     
                      <div class='form-group'>
                        <label class='col-md-3 control-label' for='description'>Mô tả</label>
                        <div class='col-md-5'>
                        	<textarea  class='form-control' type="text" id="description" name="description"><?php echo @$appsatellite['content_detail'];?></textarea>
                        </div>
                      </div>
                      <div class='form-actions form-actions-padding-sm'>
                        <div class='row'>
                          <div class='col-md-9 col-md-offset-3'>
                            <button class='btn btn-primary' onclick="return validateData()" >
                              <i class='icon-save'></i>
                              Save
                            </button>
                            <a href="<?php echo WEB_PATH.'/administrator/appsatellite';?>"><div class='btn'>Cancel</div></a>
                          </div>
                        </div>
                      </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
</div>