<?php 
	$notes = $this->notes;
	echo $this->action('slider','elements','front');
	$tr   = new Zend_Translate('ini', LANG_PATH, DEFAULT_LANGUAGE);
?>
     <div class="scroll" data-ui="jscroll-default">
     <div class='container' >
          <div class="row">
                 <div id='giaiphap-pag1-prod' >
                      <div class="row height-view-pro"></div>
                      <!-- col-lg-3 col-md-3 col-sm-12 col-xs-12 animate_afl d1 animate_start -->
                      <div class=" ani row animate_afl d1 animate_start ">
                      <br><br>
                            <div class="row ">
                                <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12 giaiphap'></div>
                                <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12' id='title_khachhang'><?php echo $notes['product0']['title'];?> </div>
                               
                            </div><!-- end row -->

                      </div><!-- class="row animate_afl d1 animate_start" -->
                     


                        </div><!-- id='giaiphap' -->
                  </div> <!-- class -row-->
    </div><!-- container-->
    <div class='container' id="giaiphap-ez2" >
 
    <div class='row  '>
       <div id="content" class="container_12">
            

      <div id="home-page" class="container content">
                   <!-- Till - block -->

            <section id="till-block" class="row">


                    <div id="slider-app">

                        <div id="tillCarousel" class="carousel slide hidden-phone" data-interval="false">

                        <div class="carousel-inner col-md-12">

                          <div class="item active  row item-doc1 hieght-pad">
                               
                                 <div class="col-md-7 pagination-centered" style="margin-left: 0;">
								  
                                  <h3 class="col-md-11 text-left-product">
                                      <i>
                                      <img src="<?php echo WEB_PATH;?>/public/front/img/ventes.png" class=" iconspan6-product re-tkiem">
                                      </i>
                                      <?php echo $notes['product1']['title'];?>
                                  </h3>
                                    <p class="text-just col-md-11">
                                      <?php echo $notes['product1']['description'];?> 
                                     </p>
          
                                  <h3 class="col-md-11 text-left-product"><i><img src="<?php echo WEB_PATH;?>/public/front/img/Rapports.png" class=" iconspan6-product re-tkiem"></i>  <?php echo $notes['product2']['title'];?></h3>
                                    <p class="text-just col-md-11"> <?php echo $notes['product2']['description'];?>  </p>

                                 <h3 class="col-md-11 text-left-product"><i><img src="<?php echo WEB_PATH;?>/public/front/img/Gerer.png" class=" iconspan6-product re-tkiem"></i><?php echo $notes['product3']['title'];?></h3>
                                    <p class="text-just col-md-11">
                                     <?php echo $notes['product3']['description'];?> 
                                    </p>
                               <div style="clear: both;"></div>
                                <h3 class='h3-span-pro' style="font-size: 32px; font-weight: bold; margin-bottom: 10px; color:#4e4e4e;"><?php echo $notes['product4']['title'];?></h3>
                                  <p class="text-just">
                                    <?php echo $notes['product4']['description'];?>  
                                  </p>
                                   
                               <h3 class='h3-span-pro-099' style="text-align: center; margin-top: 112px;"><?php echo $notes['product5']['title'];?></h3>
                                 <p class="text-just col-md-11">
                                    <?php echo $notes['product5']['description'];?>  
                                 </p>
                                  
                               </div>
                                
                                  <div class="col-md-5 pagination-centered" style="margin-left: 0;">
                                     <img src="<?php echo WEB_PATH;?>/public/front/img/iPhone5_Eng.png" alt="caisse enregistreuse caltos"  class="col-md-12" style="height: 566px; margin-bottom: 1%;margin-left: 10%;max-width: 297px;">
                                     
                                     <div  class="col-md-12 del-padding del-margin padd-l-mart" >
                                     <div class="col-md-2"></div>
                                     
                                     <div  class="col-md-8">
                                     <a href="<?php echo WEB_PATH;?>/register.html">
						               <h3 class="cta-dangki-ppro padd-l-mart"><button type="submit" class="but-minscri-product"> <?php echo $tr->translate('btn_sign_up_full');?>  </button></h3>
						               </a>
                                     </div>
                                     
                                     <div  class="col-md-2" ></div>
                                     </div>
                                </div>

                          </div><!-- class="item active row" -->
                           <div class="item   row item-doc1 hieght-pad"></div>
                           <div class="item   row item-doc1 hieght-pad"></div>

                        </div><!-- class="carousel-inner col-md-12" -->
                        

                      </div><!-- class="carousel-inner col-md-12" -->

                    </div><!-- id="tillCarousel" class="carousel slide hidden-phone" data-interval="false" -->
                
            </section>
      </div><!-- id="home-page" class="container content" -->
    </div><!-- id="content" class="container_12" -->
                        
   </div><!-- class="row" -->
</div><!-- class='container' id="giaiphap-ez2" -->
<a href="<?php echo WEB_PATH;?>/product/index/product2">next</a>
      </div>
      <script>
      $('.scroll').jscroll();
      </script>

