<?php $notes = $this->notes;?>
<div class='container box-pr-duct-p2-edit' >
	
	<!--   <div class="row height-ez2"></div> -->
	

	<div class="row">
		 <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12 tinhnang-text'></div>
	 	 <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <h3 class='tinhnang-text-h3'><?php echo $notes['smp-product0']['title'];?></h3>
          <p class='tinhnang-text-p'><?php //echo $notes['smp-product0']['description'];?></p>                
         </div><!-- span 12 -->
                          
	</div><!-- class="row" -->

	  
	 	 <div class='row  '>
                   <div class="article-tinhnang">

<div class="action-layer" data-stellar-background-ratio="0.5" data-stellar-vertical-offset="100" style="background-position: 0% -46.5px;"></div>  

                              <section id="features" class="container">     
                                  <!-- Featured Section Calls to Action -->
                                <div class="row">
                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 ez-hotro-box item animate_afc d1 animate_start">
                                      
                                      <article class="ez2-block">
                                        <div class="caption-ez2-product"> 
                                       
                                          <h3 class='ez-tn-txt-box'>
                                          <a href="<?php echo WEB_PATH;?>/product/archive" style="color: #FFFFFF;">
                                          <?php echo $notes['ordinateur']['title'];?>
                                          </a>
                                          </h3>
                                          <p class="ez-box-p-pro-edit">
                                          <?php echo $notes['ordinateur']['description'];?> 
										  </p>
                                        </div>
                                      </article>

                                    </div>

                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12  ez-hotro-box item animate_afc d2 animate_start">
                                     
                                      <article class="ez2-block">
                                        
                                        <div class="caption-ez2-product">  
                                          <h3 class='ez-tn-txt-box-1'>
                                          <a href="<?php echo WEB_PATH;?>/product/tablette" style="color: #FFFFFF;">
                                          <?php echo $notes['tablette']['title'];?>
                                          </a>
                                          </h3>
                                          <p class="ez-box-p-pro-edit">
                                           <?php echo $notes['tablette']['description'];?> 
                                           </p>
                                         
                                        </div>
                                      </article>

                                    </div>

                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12  ez-hotro-box item animate_afc d3 animate_start">
                                    
                                      <article class="ez2-block">
                                        
                                        <div class="caption-ez2-product">  
                                          <h3 class='ez-tn-txt-box-2'>
                                          <a href="<?php echo WEB_PATH;?>/product/smartphone" style="color: #FFFFFF;">
                                          <?php echo $notes['smartphone']['title'];?>
                                          </a>
                                          
                                          </h3>
                                          <p class="ez-box-p-pro-edit">
                                           <?php echo $notes['smartphone']['description'];?>
                                          </p>
                                         
                                        </div>
                                      </article>

                                    </div>


                                  </div><!-- class="row" -->
                                  <!-- End Featured Section Calls to Action -->
                                </section>

                      </div><!-- class="article-tinhnang" -->
                        
	 </div><!-- class="row" -->


</div><!-- container-->
<div class="next"><a href="<?php echo WEB_PATH;?>/product/index/product3">next</a></div>
<?php die();?>