<?php $notes = $this->notes;?>
<header id="header" class="site-header"> 
    <section id="feature_slider" class="disabled">
        <article class="slide" id="showcasing" style="background-image: url('img/backgrounds/banner-web1911.jpg'); display: block; opacity: 0.868928; background-position: 50% 0%; background-repeat: repeat no-repeat;">
            <img class="asset left-30 sp600 t120 z1" src="<?php echo WEB_PATH;?>/public/front/img/slides/scene1/macbook.png" style="left: -966px; top: 120px; z-index: 1; display: inline;">
            <div class="info" style="display: none;">
                <h2>Enregistrer 500 magasins après 120 jours - votre magasin sera 501?.</h2>
            </div>
        </article>
        <article class="slide active" id="ideas" style="background-image: url('img/backgrounds/giai-phap-tong-the_4.jpg');  display: block; background-position: 50% 0%; background-repeat: repeat no-repeat;">
            <div class="info" style="display: none;">
                <h2>Synchronisation du matériel</h2>
            </div>
            <img class="asset left-480 sp600 t260 z1" src="<?php echo WEB_PATH;?>/public/front/img/slides/scene2/left.png" style="left: 1086.8833777777777px; top: 260px; z-index: 1; display: inline;">
            <img class="asset left-210 sp600 t213 z2" src="<?php echo WEB_PATH;?>/public/front/img/slides/scene2/middle.png" style="left: 1189.7953777777777px; top: 213px; z-index: 2; display: inline;">
            <img class="asset left60 sp600 t260 z1" src="<?php echo WEB_PATH;?>/public/front/img/slides/scene2/right.png" style="left: 1292.7073777777778px; top: 260px; z-index: 1; display: inline;">
        </article>
        <article class="slide" id="tour" style="background-image: url('img/backgrounds/landscape.png');  display: none; background-position: 50% 0%; background-repeat: repeat no-repeat;">
            <img class="asset left-472 sp650 t210 z3" src="<?php echo WEB_PATH;?>/public/front/img/slides/scene3/ipad.png" style="left: -558px; top: 210px; z-index: 3; display: inline;">
            <img class="asset left-365 sp600 t270 z4" src="<?php echo WEB_PATH;?>/public/front/img/slides/scene3/iphone.png" style="left: -485px; top: 270px; z-index: 4; display: inline;">
            <img class="asset left-350 sp450 t135 z2" src="<?php echo WEB_PATH;?>/public/front/img/slides/scene3/desktop.png" style="left: -742px; top: 135px; z-index: 2; display: inline;">
            <img class="asset left-185 sp550 t220 z1" src="<?php echo WEB_PATH;?>/public/front/img/slides/scene3/macbook.png" style="left: -746px; top: 220px; z-index: 1; display: inline;">
            <div class="info" style="display: none;">
                <h2>Fonctionne sur tous les appareils</h2>
                <a href="features.html">toujours à explorer</a>
            </div>
        </article>
         <article class="slide" id="showcasing" style="background-image: url('img/backgrounds/banner-web1911.jpg'); display: block; opacity: 0.868928; background-position: 50% 0%; background-repeat: repeat no-repeat;">
            <img class="asset left-30 sp600 t120 z1" src="<?php echo WEB_PATH;?>/public/front/img/slides/scene1/macbook.png" style="left: -966px; top: 120px; z-index: 1; display: inline;">
            <div class="info" style="display: none;">
                <h2>Maybanhang.net anniversaire.</h2>
            </div>
        </article>
        <article class="slide" id="responsive" style="background-image: url('img/backgrounds/phan-cung-dong-bo_1.jpg');  display: none; background-position: 50% 0%; background-repeat: repeat no-repeat;">
            <img class="asset left-472 sp600 t120 z3" src="<?php echo WEB_PATH;?>/public/front/img/slides/scene4/html5.png" style="left: -732px; top: 120px; z-index: 3; display: inline;">
            <img class="asset left-190 sp500 t120 z2" src="<?php echo WEB_PATH;?>/public/front/img/slides/scene4/css3.png" style="left: -732px; top: 120px; z-index: 2; display: inline;">
            <div class="info" style="display: none;">
                <h3>
                  Technologie avancée <strong>HTML5 , CSS3,.... &amp; Cloud Computing</strong>
                </h3>                
            </div>
        </article> 
   
</section>
    <div class='container p-view'>
        <div class='row'>
            <div class='col-lg-1 col-md-1 col-sm-1 col-xs-12'></div>
            <div class='col-lg-11 col-md-11 col-sm-11 col-xs-12 text-view'>
                POSMANAGER.FR fournit un service fortfaitaire qui s'épaule avec les gérants du magasin de ne plus payer une grosse somme au début
            </div>
            <div class='col-lg-1 col-md-1 col-sm-1 col-xs-12'></div>
        </div>
    </div>
 </header>

  <footer id="footer" class="footer">
      <div class="container">
        <div > <!-- class="row-fluid" -->
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          
            <div class="notify-wrapper">
              <div class="notify-inner">
                <a class="notify" href="#" id='dang-ki-view'>M’INSCRIRE</a>
              </div>
            </div>
        </div>
      </div>
    </div>
  </footer>

     <div class="scroll" data-ui="jscroll-default">
        <div class='container' >
          <div class="row">
          <?php /* 
                 <div id='giaiphap-ez1' >
                      <div class="row height-view"></div>
                      <!-- col-lg-3 col-md-3 col-sm-12 col-xs-12 animate_afl d1 animate_start -->
                      <div class=" ani row animate_afl d1 animate_start">
                            <div class="row">
                                <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12 giaiphap'> Solution</div>
                                <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12' id='title_khachhang'><?php echo $notes['note1']['title']?></div>
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id='_contect_khachhang'>
                                  <p class="p-view-ttkh "><strong><?php echo $notes['note1']['description']?></strong>
                                    </p>
                                </div>
                            </div><!-- end row -->

                      </div><!-- class="row animate_afl d1 animate_start" -->
                 </div><!-- id='giaiphap' -->
           */
         ?>
           </div> <!-- class -row-->
       </div><!-- container-->
    <div class='container' id="prix-height" >
 
    <div class='row  '>
       <div id="content" class="container_12">
            

      <div id="home-page" class="container content">
                   <!-- Till - block -->

            <section id="till-block" class="row">


                    <div id="slider-app">

                        <div id="tillCarousel" class="carousel slide hidden-phone" data-interval="false">

                        <div class="carousel-inner col-md-12">

                            <div class="item active row item-doc1">
                                <div class="col-md-8 pagination-centered" style="margin-left: 0;">
                                    <img src="<?php echo WEB_PATH;?>/public/front/img/toandien.png" alt="caisse enregistreuse caltos"  class="col-md-12" style="width: 95%; max-width: 565px; margin-bottom: 1%;">
                                    <h3 class="col-md-12"><?php echo $notes['note4']['title'];?> : </h3>
                                     <p class="col-md-12">
                                        <?php echo $notes['note4']['description'];?>
                                    </p>
                                </div>
                                <div class="col-md-4" >
                                   <img src="<?php echo WEB_PATH;?>/public/front/img/01-toandien.png" class="col-md-2" style="width: 72px;height: 71px;padding: 0px; margin: 0px;">
                                    <p class="col-md-12 bold-viewez">Logiciel complet de  gestion de magasin </p>

                                    <h3 class="col-md-12 text-left"><?php echo $notes['note2']['title']?> :</h3>
                                    <p class="col-md-12">
                                        <?php echo $notes['note2']['description'];?>
                                    </p>
                                    <h3 class="col-md-12 text-left"><?php echo $notes['note3']['title']?> :</h3>
                                    <p class="col-md-12">
                                        <?php echo $notes['note3']['description'];?>
                                    </p>
                                </div>

                            </div><!-- class="item row" -->


                          <div class="item  row item-doc2">
                                 <div class="col-lg-7 col-md-7 col-sm-7 col-xs-12">
                                      <h3 class='h3-span7'><i><img src="<?php echo WEB_PATH;?>/public/front/img/icon-span6.png" class="iconspan6"></i>  <?php echo $notes['note9']['title'];?></h3>
                                      <p>  
                                         <?php echo $notes['note9']['description'];?>
                                      </p>
                                      
                                      </div><!-- span 6 -->
                                      <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12 "> 
                                        <img src="<?php echo WEB_PATH;?>/public/front/img/bg_span4.png" class='img-responsive tt-span4' >
                                      </div><!-- span 5 -->
                            </div><!-- class="item row" -->




                     <div class="item  row item-doc1">
                                 <div class="col-md-6 pagination-centered" style="margin-left: 0;">
                                     <h3 class='h3-span8'><i><img src="<?php echo WEB_PATH;?>/public/front/img/icon-tk.png" class="iconspan6 re-tkiem"></i><?php echo $notes['note10']['title'];?></h3>
                                     <img src="<?php echo WEB_PATH;?>/public/front/img/tietkiem.png" alt="caisse enregistreuse caltos"  class="col-md-12" style="width: 95%; max-width: 327px; margin-bottom: 1%;height: 361px;">
                                </div>

                                <div class="col-md-6 pagination-centered" style="margin-left: 0;">

                                  <h3 class="col-md-12 text-left" style="margin-left: 2.564102564102564%;"><?php echo $notes['note11']['title'];?></h3>
                                    <p class="col-md-11">
                                     <?php echo $notes['note11']['description'];?>
                                     </p>

                                     <h3 class="col-md-12 text-left"><?php echo $notes['note12']['title'];?></h3>
                                    <p class="col-md-11">
                                      <?php echo $notes['note12']['description'];?>
                                    </p>

                                     <h3 class="col-md-12 text-left"><?php echo $notes['note13']['title'];?></h3>
                                    <p class="col-md-11">
                                      <?php echo $notes['note13']['description'];?>
                                    </p>
                                   
                                </div>

                            </div><!-- class="item active row" -->




                          


                        </div><!-- class="carousel-inner col-md-12" -->

                        <div class="col-lg-4 col-md-4 col-sm-3 col-xs-1"></div>

                        <div class="col-lg-5 col-md-5 col-sm-6 col-xs-12 pagination-centered btn-group flot-po" data-toggle="buttons-radio" style="margin-top: 2%;">
                                <button type="button" class="btn btn active font_bt bg_bt_1  " data-target="#tillCarousel" data-slide-to="0">COMPLET</button>
                               
                                <button type="button" class="btn btn font_bt bg_bt_2 " data-target="#tillCarousel" data-slide-to="1">SIMPLE</button> 
                                
                                <button type="button" class="btn btn font_bt bg_bt_3 " data-target="#tillCarousel" data-slide-to="2">RAISONABLE</button>
                            </div><!-- end button-->

                        <div class="col-lg-3 col-md-3 col-sm-4 col-xs-2"></div>

                        </div><!-- class="carousel-inner col-md-12" -->

                    </div><!-- id="tillCarousel" class="carousel slide hidden-phone" data-interval="false" -->
                

            </section>
      </div><!-- id="home-page" class="container content" -->
    </div><!-- id="content" class="container_12" -->
                        
</div><!-- class="row" -->

</div><!-- class='container ez2-tinhnang' -->
<a href="<?php echo WEB_PATH;?>/prix/index/prix2">next</a>
      </div>
      <script>
      $('.scroll').jscroll();
      </script>

