<div class='container foottter'>
   <div class="row he-footer"></div>
   <div class="row">
         
         <div class="col-lg-5 col-md-5 col-sm-4 col-xs-3 "></div>
         <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12 "> 
            <a class="social-icons" target="_blank" href="https://twitter.com/maybanhangez?utm_source=newsletter1t1&utm_medium=email&utm_content=twiter&utm_campaign=000001_xuannganloc&accountNo&email" >
            
                <img src="<?php echo WEB_PATH;?>/public/front/img/tiwter.png" alt="facebook TacTill">
            </a>
            <a class="social-icons" target="_blank" href="https://www.facebook.com/maybanhang?utm_source=newsletter1t1&amp;utm_medium=email&amp;utm_content=facebook&amp;utm_campaign=000001_xuannganloc&amp;accountNo&amp;email" style="margin-left: 9%;">
                <img src="<?php echo WEB_PATH;?>/public/front/img/facebook.png" alt="twitter TacTill">
            </a>
              <a class="social-icons" target="_blank" href="https://plus.google.com/u/0/102742442674865133725?utm_source=newsletter1t1&utm_medium=email&utm_content=google%2B&utm_campaign=000001_xuannganloc&accountNo&email" style="margin-left: 9%;">
                <img src="<?php echo WEB_PATH;?>/public/front/img/google.png" alt="twitter TacTill">
            </a>
         </div>
         <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 "></div>
        
   </div><!-- class="row" --> 

   <div class="row">
         <div id='foottter'>
         <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12 "></div>
         <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 padd-i"> 
           <img src="<?php echo WEB_PATH;?>/public/front/img/sologen-footer.png" class="img-responsive">
         </div>
         <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 "></div>
        </div><!-- footter_ez-->  
   </div><!-- class="row" --> 
   
    <div class="row">
         <div id='foottter'>
        
         <div class="padd-i teall-ffo" style="text-align: center;margin-left: 0px; color:#bcbcbc;"> 
         120 Avondale Rd, Sinnamon Park, QLD 4073 .Contact@ezpos.com.au
         </div>
      
        </div><!-- footter_ez-->  
   </div><!-- class="row" --> 
   
  
     
  </div><!-- container-->
  
   
    <!-- Scripts -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
     <!--
     <script src='<?php echo WEB_PATH;?>/public/front/js/addclass.js'></script> -->
     <script src="<?php echo WEB_PATH;?>/public/front/js/jquery-latest.js"></script>
    <script src="<?php echo WEB_PATH;?>/public/front/js/bootstrap.min.js"></script>  
    <script src="<?php echo WEB_PATH;?>/public/front/js/theme.js"></script>
    <script type="text/javascript" src="<?php echo WEB_PATH;?>/public/front/js/index-slider.js"></script> 
    <!-- tooltip -->
     <script type="text/javascript" src='<?php echo WEB_PATH;?>/public/front/js/application.js'></script> 
    
    <script type="text/javascript" src="<?php echo WEB_PATH;?>/public/front/js/bootstrap-tooltip.js"></script>

    <!-- new js -->

    <!-- jQuery REVOLUTION Slider  -->
    <script type="text/javascript" src="<?php echo WEB_PATH;?>/public/front/js/jquery.themepunch.plugins.min.js"></script>
    <script type="text/javascript" src="<?php echo WEB_PATH;?>/public/front/js/jquery.themepunch.revolution.min.js"></script>
    <!-- jQuery way points -->
    <script src="<?php echo WEB_PATH;?>/public/front/js/waypoints.min.js"></script>
    <!-- Jquery for Countdown Watch -->
    <script type="text/javascript" src="<?php echo WEB_PATH;?>/public/front/js/jquery.countdown.min.js"></script>
    <!-- Portfolio JS -->
    <!-- Pretty Photo, Filter And Isotope JS -->
    <script type="text/javascript" src="<?php echo WEB_PATH;?>/public/front/js/filter.js"></script>
    <script type="text/javascript" src="<?php echo WEB_PATH;?>/public/front/js/isotope.js"></script>
    <script type="text/javascript" src="<?php echo WEB_PATH;?>/public/front/js/jquery.prettyPhoto.js"></script>
   
    <!-- Respond JS for IE8 -->
    <script type="text/javascript" src="<?php echo WEB_PATH;?>/public/front/js/respond.min.js"></script>
    <!-- HTML5 Support for IE -->
    <script type="text/javascript" src="<?php echo WEB_PATH;?>/public/front/js/html5shiv.js"></script>
    <!-- Custom JS -->
 <!--    <script type="text/javascript" src="<?php echo WEB_PATH;?>/public/front/js/custom.js"></script> -->
    <script type="text/javascript" src="<?php echo WEB_PATH;?>/public/front/js/remove_add_active.js"></script>
    <script type="text/javascript" src="<?php echo WEB_PATH;?>/public/front/js/process-front.js"></script>
    <script type="text/javascript" src="<?php echo WEB_PATH;?>/public/front/js/navvi_hover_li_a.js "></script>   
    
