<div id="footer_adv" class="s1000">
			<div class="footer_adv_box">
				<div class="footer_adv fl"><img alt="" src="<?php echo WEB_PATH?>/public/images/banner.jpg"></div>
				<div class="footer_adv fl"><img alt="" src="<?php echo WEB_PATH?>/public/images/banner.jpg"></div>
				<div class="footer_adv fl"><img alt="" src="<?php echo WEB_PATH?>/public/images/banner.jpg"></div>
				<div class="cb"></div>
			</div>
		</div>