<div class="adv4">
	<a
		href="<?php echo WEB_PATH;?>/chuyen-muc/he-sinh-thai-php-6.html"><img
		alt="Hệ sinh thái PHP. Apache - Linux server - Những kiến thức liên quan"
		title="Hệ sinh thái PHP. Apache - Linux server - Những kiến thức liên quan"
		src="<?php echo WEB_PATH?>/public/images/he-sinh-thai-php.png">
	</a>
	
	<a
		href="<?php echo WEB_PATH;?>/chuyen-muc/khoi-nghiep-7.html"><img
		alt="Khởi nghiệp. Những bài học về khởi nghiệp."
		title="Khởi nghiệp. Những bài học về khởi nghiệp."
		src="<?php echo WEB_PATH?>/public/images/khoi-nghiep.jpg">
	</a>
	
</div>
