<div class="adv1">
	<a
		href="<?php echo WEB_PATH;?>/dao-tao-lap-trinh-vien-php-seo-day-lam-web-voi-giang-vien-7-nam-kinh-nghiem.html"><img
		alt="Đào tạo lập trình viên PHP-SEO-SEM-Socal Marketing. Giảng viên: Hán Anh Vũ - 7 năm kinh nghiệm lập trình web"
		title="Đào tạo lập trình viên PHP-SEO-SEM-Socal Marketing. Giảng viên: Hán Anh Vũ - 7 năm kinh nghiệm lập trình web"
		src="<?php echo WEB_PATH?>/public/images/goodgood.vn-dao-tao-lap-trinh-vien-php-giang-vien-7-nam-kinh-nghiem-tai-cac-tap-doan-da-quoc-gia-0936807207.png">
	</a>
</div>
