<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container fix-full-ez">
         
          
                <div class="navbar-header header-sty">
                  <a href="index.html" class="navbar-brand"><img class='logo_ez img-responsive' src="<?php echo WEB_PATH;?>/public/front/img/logo-vesti.png" ></a>
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="navbar-ex1-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
               </div><!-- class="navbar-header" --> 

               <div class="collapse navbar-collapse navbar-ex1-collapse  " role="navigation"> <!-- class= "menu" -->
                    <ul class="nav navbar-nav navbar-right nav_top" id="topnav">
                        <li class=""><a href="<?php echo WEB_PATH;?>/home.html">ACCUEIL</a></li>
                        <li><a href="<?php echo WEB_PATH;?>/product.html">PRODUIT</a>
				            <span>
				                <a href="">The Company</a> |
				                <a href="">The Team</a> |
				                <a href="">Careers</a>
				            </span>
				        </li>
                        <li><a href="#">SOLUTIONS</a></li>
                        <li><a href="<?php echo WEB_PATH;?>/prix">PRIX</a>
                        	 <span>
					                <a href="">What We Do</a> |
					                <a href="">Our Process</a> |
					                <a href="">Testimonials</a>
					            </span>
                        </li>
                        <li><a href="#">MATÉRIEL</a></li>
                        <li><a href="#">TÉLÉCHARGER</a></li>
                        <li><a href="<?php echo WEB_PATH;?>/register.html" id='color1-menu'>M'INSCRIRE</a></li>
                        <li><a href="http://quanly.maybanhang.net/" id='color-menu'>CONNEXION</a></li>

                    </ul>
                 </div><!--  class="collapse navbar-collapse navbar-ex1-collapse" role="navigation" -->

            </div><!-- class="container"-->


        </div>