  <?php $notes = $this->notes;
  $tr   = new Zend_Translate('ini', LANG_PATH, DEFAULT_LANGUAGE);
  $notes_table = $this->notes_table?>
   <header id="header" class="site-header-smartphone " > <!-- class="site-header"  -->
   
     <?php 
        // menu 
        echo $this->action('topmenu','elements','front');
     ?>
 
   </header>

  <footer id="footer" class="footer">
   
 
      <div class="container">
      <?php  /*
        <div > <!-- class="row-fluid" -->
          <div class="col-lg-12 col-lg-12 col-md-12 col-sm-12 col-xs-12 col-sm-12 col-xs-12">
          
            <div class="notify-wrapper">
              <div class="notify-inner">
                <a class="notify" href="#" id='dang-ki-view'>M’INSCRIRE</a>
              </div>
            </div>
        </div>
      </div>
      */
    ?>
    </div>
 
  </footer>
<div id="menu">
  
     <div class="scroll" data-ui="jscroll-default">
     
    <div class='container' >
          <div class="row">
                 <div id='giaiphap-pag1-prod' >
                      <div class="row height-view-pro"></div>
                      <!-- col-lg-3 col-lg-3 col-md-3 col-sm-12 col-xs-12 col-sm-12 col-xs-12 animate_afl d1 animate_start -->
                      <div class=" ani row animate_afl d1 animate_start ">
                            <div class="row ">
                                <div class='col-lg-12 col-lg-12 col-md-12 col-sm-12 col-xs-12 col-sm-12 col-xs-12 gp-viet-table-1'>
                                
                                <?php echo $notes['tablette0']['title'];?></div>
                                <div class='col-lg-12 col-lg-12 col-md-12 col-sm-12 col-xs-12 col-sm-12 col-xs-12' id='title_khachhang'></div>
                                <p class="text-just-smp col-md-11 " >
                                <?php echo $notes['tablette0']['description'];?> 
                                </p>
                            </div><!-- end row -->

                      </div><!-- class="row animate_afl d1 animate_start" -->
                     


                        </div><!-- id='giaiphap' -->
                  </div> <!-- class -row-->
    </div><!-- container-->
    <div class='container' id="page-01-tablette-of-hei" >
 
    <div class='row  '>
       <div id="content" class="container_12">
            

      <div id="home-page" class="container content">
                   <!-- Till - block -->

            <section id="till-block" class="row">

                        <div class=" carousel-inner-bkoff col-lg-12 col-md-12 col-sm-12 col-xs-12">

                          <div class="item active  row page01-bkooffice " >
                               
                                 
								
								 <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 pagination-centered" style="margin-left: 0;">
                                     <div  class="col-lg-4 col-md-4 col-sm-12 col-xs-12 del-padding del-margin" >
                                     	 
				                                  <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-left-tablete">
				                                     <i><img src="<?php echo WEB_PATH;?>/public/front/img/Toutes_les.png" class=" icon-table re-tkiem"></i>
				                                    <?php echo $notes['tablette1']['title'];?>
				                                  </h3>
				                                    <p class="text-just col-lg-12 col-md-12 col-sm-12 col-xs-12">
				                                    <?php echo $notes['tablette1']['description'];?> 
				                                     </p>
			                                
			                                   
			                              
				          					       <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-left-tablete">
				                                     <i><img src="<?php echo WEB_PATH;?>/public/front/img/Points_de.png" class=" icon-table re-tkiem"></i>
				                                      <?php echo $notes['tablette2']['title'];?>
				                                   </h3>
				                                     <p class="text-just col-lg-12 col-md-12 col-sm-12 col-xs-12">
				                                      <?php echo $notes['tablette2']['description'];?> 
				                                      </p>
			                               
			                                  
			                                   
				          					       <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-left-tablete">
				                                     <i><img src="<?php echo WEB_PATH;?>/public/front/img/icon-table.png" class=" icon-table re-tkiem"></i>
				                                      <?php echo $notes['tablette3']['title'];?>
				                                   </h3>
				                                     <p class="text-just col-lg-12 col-md-12 col-sm-12 col-xs-12">
				                                      <?php echo $notes['tablette3']['description'];?> 
				                                      </p>
			                                
			                           
                                     </div>
                                     
                                     <div  class="col-md-7 del-padding del-margin" >
	                                       <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"> 
	                                          <img src="<?php echo WEB_PATH;?>/public/front/img/02-img-table.png"  class=" img-responsive " >
	                                       </div>
	                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">     
			                                     <div  class="col-lg-5 col-md-5 col-sm-12 col-xs-12" ></div>
			                                     <div  class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
			                                       <a href="<?php echo WEB_PATH;?>/register.html">
			                                     <h3 class="iphone-view-smartphone-02"><?php echo $tr->translate('btn_sign_up_full');?></h3>
			                                     </a>
			                                     </div>
			                                     <div  class="col-lg-4 col-md-4 col-sm-12 col-xs-12" ></div>
		                                    </div>
                                      </div>
                                    
                                 </div>
                                
								
								
                                 
                               
                                
                                 

                          </div><!-- class="item active row" -->
                          

                        </div><!-- class="carousel-inner col-lg-12 col-md-12 col-sm-12 col-xs-12" -->
                        

                 

                 
                
            </section>
      </div><!-- id="home-page" class="container content" -->
    </div><!-- id="content" class="container_12" -->
                        
   </div><!-- class="row" -->
</div><!-- class='container' id="giaiphap-ez2" -->

	<?php // echo $this->layout()->content;?>
     <a href="<?php echo WEB_PATH;?>/product/tablette/tablette2">next</a>
     
 </div><!-- class="scroll" data-ui="jscroll-default" -->
      <script>
      $('.scroll').jscroll();
      </script>
 