<?php $notes = $this->notes;
$tr   = new Zend_Translate('ini', LANG_PATH, DEFAULT_LANGUAGE);
?>
   <div class='container' >
          <div class="row">
                 <div id='giaiphap-pag03-table' >
                      <div class="row height-view-pro"></div>
                      <!-- col-lg-3 col-md-3 col-sm-12 col-xs-12 animate_afl d1 animate_start -->
                      <div class=" ani row animate_afl d1 animate_start ">
                            <div class="row col-lg-12 col-md-12 col-sm-12 col-xs-12 height-tablebk-page-03">
	                            <div class="col-lg-8 col-md-7 col-sm-12 col-xs-12 pad-cod-8">
	                                    <p class="text-just col-lg-12 col-md-12 col-sm-12 col-xs-12">
	                                       <?php echo $notes['tablette5']['title'];?>
	                                     </p>
	                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">  
			                                     <div  class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
			                                       <a href="<?php echo WEB_PATH;?>/register.html">
			                                     <h3 class="cta-table-01"> <?php echo $tr->translate('btn_sign_up_full');?></h3>
			                                     </a>
			                                     </div>
			                                     <div  class="col-lg-6 col-md-6 col-sm-12 col-xs-12" >
			                                     
			                                     <a href="#">
			                                     <h3 class="cta-table-02" style="font-family: Arial; text-transform: uppercase;"> <?php echo $tr->translate('btn_watch_video');?></h3>
			                                     </a>
			                                     </div>
		                                 </div>
	                              </div>
                              
                                 <div class='col-lg-4 col-md-5 col-sm-12 col-xs-12 del-padding '>
                                  <div class="div-video animate_afl d2 animate_start">
                                       <?php echo $notes['tablette5']['description'];?> </p></div>
                                 </div>
                            </div><!-- end row -->

                      </div><!-- class="row animate_afl d1 animate_start" -->
                     


                        </div><!-- id='giaiphap' -->
                  </div> <!-- class -row-->
    </div><!-- container-->

<div class="next"><a href="<?php echo WEB_PATH;?>/product/tablette/tablette4">next</a></div>
<?php die();?>