<?php $notes = $this->notes;?>

    <div class='container' id="giaiphap-ez2" >
 	
 	 <div class="row">
                 <div id='page-04-tables' >
                      <div class="row height-table-v-012"></div>
                      <!-- col-lg-3 col-md-3 col-sm-12 col-xs-12 animate_afl d1 animate_start -->
                      <div class=" ani row animate_afl d1 animate_start ">
                            <div class="row col-lg-12 col-md-12 col-sm-12 col-xs-12 height-tablebk-page-03">
	                           
	                                  <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-lfet-tablete">
	                                    <?php echo $notes['tablette6']['title'];?>
	                                  </h3>
	                             
	                               <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 del-padding">
	                               
	                                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 height-able">
	                                     <p class="text-just col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
	                                       <?php echo $notes['tablette6']['description'];?> 
	                                     </p>
	                                </div>
	                                
	                                <div class='col-lg-6 col-md-6 col-sm-12 col-xs-12 padd-ed-table-02 '>
		                                <div class="img-table-04 animate_afl d2 animate_start">
		                                 <img src="<?php echo WEB_PATH;?>/public/front/img/img-table-04-v.png"   class="img-responsive" />
	                                    </div>
                                      </div>
                                    
	                               </div><!-- class="col-lg-12 col-md-12 col-sm-12 col-xs-12 del-padding"  -->
	                                    
	                            
                              
                                
                            </div><!-- end row -->

                      </div><!-- class="row animate_afl d1 animate_start" -->
                     


                        </div><!-- id='giaiphap' -->
                  </div> <!-- class -row-->
 	
 	
    <div class='row  '>
       <div id="content" class="container_12">
            

      <div id="page-04-02-table-view" class="container content">
                   <!-- Till - block -->

            <section id="till-block" class="row">


                    <div id="slider-app">

                        <div id="tillCarousel" class="carousel slide hidden-phone" data-interval="false">

                        <div class="carousel-inner col-lg-12 col-md-12 col-sm-12 col-xs-12">
							 <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-h3-table">
	                               <?php echo $notes['tablette7']['title'];?>
	                         </h3>
	                         
                          <div class="item active  row item-doc-tables-edit ">
                               
                                 <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 pagination-centered" style="margin-left: 0;">
								  <div class="view-tanble-07">
	                                  <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-h03-tbale">
	                                     <i><img src="<?php echo WEB_PATH;?>/public/front/img/icon-left-table.png" class=" iconspan6 re-tkiem"></i>
	                                    <?php echo $notes['tablette8']['title'];?>
	                                  </h3>
	                                    <p class="text-just col-lg-12 col-md-12 col-sm-12 col-xs-12">
	                                    <?php echo $notes['tablette8']['description'];?> 
	                                     </p>
                                  </div><!-- view-tanble-07 -->   
                                   
                                  <div class="view-tanble-07">    
          						 <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-h03-tbale">
                                     <i><img src="<?php echo WEB_PATH;?>/public/front/img/icon-left-table.png" class=" iconspan6 re-tkiem"></i>
                                      <?php echo $notes['tablette9']['title'];?>
                                   </h3>
                                     <p class="text-just col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                      <?php echo $notes['tablette9']['description'];?> 
                                      </p>
                                  </div><!-- view-tanble-07 -->
                                  
								</div>
								
								 <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 pagination-centered " >
								  <div class="view-tanble-07">   
                                     <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-h03-tbale">
                                     <i><img src="<?php echo WEB_PATH;?>/public/front/img/icon-left-table.png" class=" iconspan6 re-tkiem"></i>
                                    <?php echo $notes['tablette10']['title'];?>
                                    </h3>
                                    <p class="text-just col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <?php echo $notes['tablette10']['description'];?> 
                                     </p>
                                    </div>
                                    
                                     <div class="view-tanble-07">   
	          						 <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-h03-tbale">
	                                     <i><img src="<?php echo WEB_PATH;?>/public/front/img/icon-left-table.png" class=" iconspan6 re-tkiem"></i>
	                                      <?php echo $notes['tablette11']['title'];?>
	                                   </h3>
	                                     <p class="text-just col-lg-12 col-md-12 col-sm-12 col-xs-12">
	                                      <?php echo $notes['tablette11']['description'];?> 
	                                      </p>
	                                      
	                                  </div>
	                                  
                                  </div>
								
								 <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 pagination-centered" style="margin-left: 0;">
								 
								  <div class="view-tanble-07">   
                                   <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-h03-tbale">
                                     <i><img src="<?php echo WEB_PATH;?>/public/front/img/icon-left-table.png" class=" iconspan6 re-tkiem"></i>
                                    <?php echo $notes['tablette12']['title'];?>
                                  </h3>
                                    <p class="text-just col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <?php echo $notes['tablette12']['description'];?> 
                                     </p>	
                                     </div>
                                     
                                      <div class="view-tanble-07">   
		          						 <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-h03-tbale">
		                                     <i><img src="<?php echo WEB_PATH;?>/public/front/img/icon-left-table.png" class=" iconspan6 re-tkiem"></i>
		                                      <?php echo $notes['tablette13']['title'];?>
		                                   </h3>
		                                     <p class="text-just col-lg-12 col-md-12 col-sm-12 col-xs-12">
		                                      <?php echo $notes['tablette13']['description'];?> 
		                                      </p>
                                      </div>
                                      
                                  </div>
                                 
                               
                                
                                 

                          </div><!-- class="item active row" -->
                           

                        </div><!-- class="carousel-inner col-lg-12 col-md-12 col-sm-12 col-xs-12" -->
                        

                      </div><!-- class="carousel-inner col-lg-12 col-md-12 col-sm-12 col-xs-12" -->

                    </div><!-- id="tillCarousel" class="carousel slide hidden-phone" data-interval="false" -->
                
            </section>
      </div><!-- id="home-page" class="container content" -->
    </div><!-- id="content" class="container_12" -->
                        
   </div><!-- class="row" -->
</div><!-- class='container' id="giaiphap-ez2" -->
<div class="next"><a href="<?php echo WEB_PATH;?>/product/tablette/tablette5">next</a></div>
<?php die();?>