 <?php $notes = $this->notes;
 $tr   = new Zend_Translate('ini', LANG_PATH, DEFAULT_LANGUAGE);
 ?>
    <div class='container' >
          <div class="row">
                 <div id='gp-page-06-table' >
                      <div class="row height-view-pro"></div>
                      <!-- col-lg-3 col-md-3 col-sm-12 col-xs-12 animate_afl d1 animate_start -->
                      <div class=" ani row animate_afl d1 animate_start ">
                            <div class="row  ">
                             <!-- 
                                <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12 giaiphap'><?php echo $notes['tablette14']['title'];?></div>
                                <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12' id='title_khachhang'></div>
                                <p class="text-just-smp col-md-11 " >
                                <?php echo $notes['tablette14']['description'];?> 
                                </p>
                            -->  
                                
                            </div><!-- end row -->
                            	<div class="col-md-12 pagination-centered" style="margin-left: 0;">     
                                    <div  class="col-md-3" ></div>
                                     <div  class="col-md-5"><h3 class="iphone-p-acr" style="text-transform: uppercase;">
                                     <a href="<?php echo WEB_PATH;?>/product.html">
                                     <?php echo $tr->translate('btn_review_features');?>
                                     </a>
                                     </h3>
                                     </div>
                                     <div  class="col-md-4" ></div>
                                  </div>
                                  <div style="clear: both;"></div>
                              <div class="col-md-12 pagination-centered">     
                                    <div  class="col-lg-4 col-md-4 col-sm-12 col-xs-12" ></div>
                                     <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                                       <a href="<?php echo WEB_PATH;?>/register.html">
                                     	<h3 class="cta-table-pag05_1"> <?php echo $tr->translate('btn_sign_up_full');?></h3>
                                     </a>
                                     </div>
                                     <div  class="col-lg-4 col-md-4 col-sm-12 col-xs-12" ></div>
                                  </div>

                      </div><!-- class="row animate_afl d1 animate_start" -->
      
                        </div><!-- id='giaiphap' -->
                  </div> <!-- class -row-->
                  
                  
    </div><!-- container-->
 
<div class="next"><a href="<?php echo WEB_PATH;?>/product/tablette/tablette6">next</a></div>
<?php die();?>                   