<?php $notes = $this->notes;?>
<div class='container' >
          <div class="row">
                 <div id='giaiphap-ez1-prod' >
                      <div class="row height-view-pro"></div>
                      <!-- col-lg-3 col-md-3 col-sm-12 col-xs-12 animate_afl d1 animate_start -->
                      <div class=" ani row animate_afl d1 animate_start ">
                            <div class="row ">
                                <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12 giaiphap'></div>
                                <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12' id='title_khachhang'>
                                 <?php echo $notes['tablette4']['title'];?>
                                </div>
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id='_contect_khachhang'>
                                  <p class="p-view-ttkh ">
                                   <?php echo $notes['tablette4']['description'];?> </p>
                                </div>
                                
                               
                            </div><!-- end row -->

                      </div><!-- class="row animate_afl d1 animate_start" -->
                     


                        </div><!-- id='giaiphap' -->
                  </div> <!-- class -row-->
    </div><!-- container-->
    <div class='container' id="gp-tabletet03" >
 
    <div class='row  '>
       <div id="content" class="container_12">
            

      <div id="home-page" class="container content">
                   <!-- Till - block -->

            <section id="till-block" class="row">


                    <div id="slider-app">

                        <div id="tillCarousel" class="carousel slide hidden-phone" data-interval="false">

                        <div class="carousel-inner col-md-12">
							
                             <div class="item active  row item-doc1 ">
                                  <div class="col-lg-7 col-md-7 col-sm-12 col-xs-12 del-padding-5px  pagination-centered" style="margin-left: 0;">
                                     <img src="<?php echo WEB_PATH;?>/public/front/img/03-img-table.png" alt="caisse enregistreuse caltos"  class="img-responsive animate_afl d2 animate_start" style="width: 100%; max-width:607px ; height:480px ;margin:0px;">
	                                 
                                   </div>
                                   
                                 <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12 pagination-centered del-padding" style="margin-left: 0;">
								 
                                    <ul class="ul-tabl-04 col-md-12 animate_afl d4 animate_start pad-top-tab ">
                                    	<li ><img src="<?php echo WEB_PATH;?>/public/front/img/ul-li-table.png" class="img-li-tabl-ul-04 ">
                                    	<p>Manage booked sittings and menu.</p>
                                    	</li>
                                    	<li><img src="<?php echo WEB_PATH;?>/public/front/img/ul-li-table.png" class="img-li-tabl-ul-04 ">
                                    	<p>Show and tell about menu items with photos and notes.</p>
                                    	</li>
                                    	<li><img src="<?php echo WEB_PATH;?>/public/front/img/ul-li-table.png" class="img-li-tabl-ul-04 ">
                                    	<p class="view-p-tablef">Merge, change between tables.</p>
                                    	</li>
                                    	<li ><img src="<?php echo WEB_PATH;?>/public/front/img/ul-li-table.png" class="img-li-tabl-ul-04 ">
                                    	<p>Print estimated invoice and kitchen slip by handheld bluetooth printers</p>
                                    	</li>
                                    	
                                    </ul>
                                   
                                      
                               
                                  </div>
                                 
                                  
                                  
                                
                           

                          </div><!-- class="item active row" -->
                           
                          

                        </div><!-- class="carousel-inner col-md-12" -->
                        

                      </div><!-- class="carousel-inner col-md-12" -->

                    </div><!-- id="tillCarousel" class="carousel slide hidden-phone" data-interval="false" -->
                
            </section>
      </div><!-- id="home-page" class="container content" -->
    </div><!-- id="content" class="container_12" -->
                        
   </div><!-- class="row" -->
</div><!-- class='container' id="giaiphap-ez2" -->
<div class="next"><a href="<?php echo WEB_PATH;?>/product/tablette/tablette3">next</a></div>
<?php die();?>