<?php $notes = $this->notes;
$tr   = new Zend_Translate('ini', LANG_PATH, DEFAULT_LANGUAGE);
?>
<div class="report-bc-smphone">
<div class='container' >
<?php 
   /*
          <div class="row">
                 <div id='quanlycuahang-prod' >
                      <div class="row height-view-pro"></div>
                      <!-- col-lg-3 col-md-3 col-sm-12 col-xs-12 animate_afl d1 animate_start -->
                      <div class=" ani row animate_afl d1 animate_start ">
                            <div class="row ">
                                <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12 giaiphap'></div>
                                <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12' id='title_khachhang'>Rapports de magasin</div>
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id='_contect_khachhang'>
                                  <p class="p-view-ttkh "></p>
                                </div>
                               
                            </div><!-- end row -->

                      </div><!-- class="row animate_afl d1 animate_start" -->
                     


                        </div><!-- id='giaiphap' -->
          </div> <!-- class -row-->
   */
?>

   
    </div><!-- container-->
    <div class='container' id="bk-smp-phone03" >
 
    <div class='row  '>
       <div id="content" class="container_12">
            

      <div id="home-page" class="container content">
                   <!-- Till - block -->

            <section id="till-block" class="row">


                    <div id="slider-app">

                        <div id="tillCarousel" class="carousel slide hidden-phone" data-interval="false">

                        <div class="carousel-inner col-lg-12 col-md-12 col-sm-12 col-xs-12">

                          <div class="item active  row item-page5 ">
                                 
                                  <div class="col-lg-6 col-md-5 col-sm-6 col-xs-12 pagination-centered  " >
                                     <img src="<?php echo WEB_PATH;?>/public/front/img/aliceBoutique.png" alt="caisse enregistreuse caltos"  class="col-md-12 animate_afl d1 animate_start" style="padding: 0px;margin: 0px; width: 100%; max-width: 405px;height: 313px;">
                                     
                                  </div>
                                
                                 <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 pagination-smart03" >
                                   <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12 h3-smartphone"> <?php echo $notes['smartphone12']['title'];?></3>
								   <p class="text-smartphone-01 col-lg-11 col-md-11 col-sm-11 col-xs-12">
								    <?php echo $notes['smartphone12']['description'];?> 
                                   </p>
          						
          							 <div class="col-md-12" >
          							 
          							   <a href="<?php echo WEB_PATH;?>/register.html">
	                                    <h3 class="iphone-view-smartphone-05 cta-smartphone-01">
	                                    <?php echo $tr->translate('btn_sign_up_full');?>
	                                    </h3>
	                                    </a> 
                                     </div>
                                     
                                </div>
                                
                                
                                
                           

                          </div><!-- class="item active row" -->
                           <div class="item   row item-page5 "></div>
                           <div class="item   row item-page5 "></div>

                        </div><!-- class="carousel-inner col-md-12" -->
                        

                      </div><!-- class="carousel-inner col-md-12" -->

                    </div><!-- id="tillCarousel" class="carousel slide hidden-phone" data-interval="false" -->
                
            </section>
      </div><!-- id="home-page" class="container content" -->
    </div><!-- id="content" class="container_12" -->
                        
   </div><!-- class="row" -->
  </div><!-- class='container' id="giaiphap-ez2" -->
</div><!-- report-bc -->
  <div class='container' >
          <div class="row">
                 <div id='acr-last' >
                      <div class="row height-view-pro"></div>
                      <!-- col-lg-3 col-md-3 col-sm-12 col-xs-12 animate_afl d1 animate_start -->
                      <div class=" ani row animate_afl d1 animate_start ">
                           
                              <div class="col-md-12 pagination-centered" style="margin-left: 0;">     
                                    <div  class="col-md-3" ></div>
                                     <div  class="col-md-5"><h3 class="iphone-p-acr" style="text-transform: uppercase;">
                                     <a href="<?php echo WEB_PATH;?>/product.html">
                                     <?php echo $tr->translate('btn_review_features');?>
                                     </a>
                                     </h3>
                                     </div>
                                     <div  class="col-md-4" ></div>
                                  </div>

                      </div><!-- class="row animate_afl d1 animate_start" -->
       <div class="row" style="height: 40px;"></div>
                        </div><!-- id='giaiphap' -->
                  </div> <!-- class -row-->
                  
    </div><!-- container-->
   
<div class="next"><a href="<?php echo WEB_PATH;?>/product/smartphone/smartphone4">next</a></div>
<?php die();?>