<?php $notes = $this->notes;
$tr   = new Zend_Translate('ini', LANG_PATH, DEFAULT_LANGUAGE);
?>
<div class='container' >
          <div class="row">
                 <div id='giaiphap-ez1-prod' >
                      <div class="row height-view-pro"></div>
                      <!-- col-lg-3 col-md-3 col-sm-12 col-xs-12 animate_afl d1 animate_start -->
                      <div class=" ani row animate_afl d1 animate_start ">
                            <div class="row ">
                                <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12 giaiphap'></div>
                                <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12' id='title_khachhang'>
                                <?php echo $notes['smartphone5']['title'];?>
                                </div>
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id='_contect_khachhang'>
                                  <p class="p-view-ttkh "><?php echo $notes['smartphone5']['description'];?> </p>
                                </div>
                               
                            </div><!-- end row -->

                      </div><!-- class="row animate_afl d1 animate_start" -->
                     


                        </div><!-- id='giaiphap' -->
                  </div> <!-- class -row-->
    </div><!-- container-->
    <div class='container' id="giaiphap-product" >
 
    <div class='row  '>
       <div id="content" class="container_12">
            

      <div id="home-page" class="container content">
                   <!-- Till - block -->

            <section id="till-block" class="row">


                    <div id="slider-app">

                        <div id="tillCarousel" class="carousel slide hidden-phone" data-interval="false">

                        <div class="carousel-inner col-md-12">

                          <div class="item active  row item-doc1 hieght-pad">
                              
                                 <div class="col-md-6 pagination-centered" style="margin-left: 0;">
								  
                                  <h3 class="col-md-12 text-smartp">
                                  <?php echo $notes['smartphone6']['title'];?>
                                  </h3>
                                    <p class="text-just-neu-edit col-md-12">
                                    <?php echo $notes['smartphone6']['description'];?> 
                                    </p>
                                     
                                   
                                     
							      <h3 class="col-md-12 text-smartp">
							      <?php echo $notes['smartphone7']['title'];?>
							      </h3>
                                    <p class="text-just-neu-edit col-md-12">
                                    <?php echo $notes['smartphone7']['description'];?> 
                                    </p>
                                    
                                      
                                 <h3 class="col-md-12 text-smartp">
                                 <?php echo $notes['smartphone8']['title'];?>
                               
                                 </h3>
                                    <p class="text-just-neu-edit col-md-12">
                                       <?php echo $notes['smartphone8']['description'];?> 
                                     </p>
                                     
                                      
                                 <h3 class="col-md-12 text-smartp">
                                 <?php echo $notes['smartphone9']['title'];?>
                                 </h3>
                                    <p class="text-just-neu-edit col-md-12">
                                     <?php echo $notes['smartphone9']['description'];?> 
                                     </p>
                                      
                                      
                                <h3 class="col-md-12 text-smartp"> <?php echo $notes['smartphone10']['title'];?> </h3>
                                    <p class="text-just-neu-edit col-md-12">
                                     <?php echo $notes['smartphone10']['description'];?> 
                                     </p>
                                     
                                     
                                   <h3 class="col-md-12 text-smartp"><?php echo $notes['smartphone11']['title'];?></h3>
	                                    <p class="text-just col-md-12">
	                                      <?php echo $notes['smartphone11']['description'];?> 
	                                    </p>   
                                      
                                      
                                  </div>
                                 
                                  
                                   <div class="col-md-6 pagination-centered" style="margin-left: 0;">
                                     <img src="<?php echo WEB_PATH;?>/public/front/img/Fonctions.png" alt="caisse enregistreuse caltos"  class="col-md-12 animate_afl d2 animate_start" style="width: 100%; max-width:467px ; height:459px ;margin-top: -1%;">
	                                 <div class="col-md-12" >
	                                   <a href="<?php echo WEB_PATH;?>/register.html">
	                                    <h3 class="iphone-view-smartphone-02 cta-smartphone">
	                                    	<?php echo $tr->translate('btn_sign_up_full');?>
	                                    </h3>
	                                    </a> 
                                     </div>
                                      
                                   </div>
                                
                           

                          </div><!-- class="item active row" -->
                           <div class="item   row item-doc1 hieght-pad"></div>
                           <div class="item   row item-doc1 hieght-pad"></div>

                        </div><!-- class="carousel-inner col-md-12" -->
                        

                      </div><!-- class="carousel-inner col-md-12" -->

                    </div><!-- id="tillCarousel" class="carousel slide hidden-phone" data-interval="false" -->
                
            </section>
      </div><!-- id="home-page" class="container content" -->
    </div><!-- id="content" class="container_12" -->
                        
   </div><!-- class="row" -->
</div><!-- class='container' id="giaiphap-ez2" -->
<div class="next"><a href="<?php echo WEB_PATH;?>/product/smartphone/smartphone3">next</a></div>
<?php die();?>