 <?php $notes = $this->notes;
 $tr   = new Zend_Translate('ini', LANG_PATH, DEFAULT_LANGUAGE);
 ?>
    <div class='container' >
          <div class="row">
                 <div id='gp-page-06-market' >
                      <div class="row height-view-pro"></div>
                      <!-- col-lg-3 col-md-3 col-sm-12 col-xs-12 animate_afl d1 animate_start -->
                      <div class=" ani row animate_afl d1 animate_start ">
                           
                              <div class="col-md-12 pagination-centered" style="margin-left: 0;">     
                                    <div  class="col-md-3" ></div>
                                    
                                     <div  class="col-md-5">
                                     <a href="#">
                                     <h3 class="iphone-p-05-mart" style="text-transform: uppercase;"><a href="<?php echo WEB_PATH;?>/product.html"><?php echo $tr->translate('btn_review_features');?></a></h3>
                                     </a>
                                     </div>
                                     <div  class="col-md-4" ></div>
                                  </div>

                      </div><!-- class="row animate_afl d1 animate_start" -->
      
                        </div><!-- id='giaiphap' -->
                  </div> <!-- class -row-->
                  
                  
    </div><!-- container-->
 
<div class="next"><a href="<?php echo WEB_PATH;?>/product/marketing/marketing6">next</a></div>
<?php die();?>                   