<?php $notes = $this->notes;?>
<div class='container' >
          <div class="row">
                 <div id='giaiphap-01-martket' >
                      <div class="row height-view-pro"></div>
                      <!-- col-lg-3 col-md-3 col-sm-12 col-xs-12 animate_afl d1 animate_start -->
                      <div class=" ani row animate_afl d1 animate_start ">
                            <div class="row ">
                                <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12 gp-viet-table-1'><?php echo $notes['marketing5']['title'];?></div>
                                <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12' id='title_khachhang'></div>
                                <p class="text-just-smp col-md-11 " >
                                <?php echo $notes['marketing5']['description'];?> 
                                </p>
                            </div><!-- end row -->

                      </div><!-- class="row animate_afl d1 animate_start" -->
                     


                        </div><!-- id='giaiphap' -->
                  </div> <!-- class -row-->
    </div><!-- container-->
    <div class='container' id="page-01-martk" >
 
    <div class='row  '>
       <div id="content" class="container_12">
            

      <div id="home-page" class="container content">
                   <!-- Till - block -->

            <section id="till-block" class="row">

                        <div class="  col-md-12">

                          <div class="item active  row page01-bkooffice " >
                               <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
				                                  <h3 class="text-left-tablete">
				                                     <i><img src="<?php echo WEB_PATH;?>/public/front/img/icon-mark.png" class=" icon-martketting re-tkiem-edit"></i>
				                                    <?php echo $notes['marketing6']['title'];?>
				                                  </h3>
				                                    <p class="text-just col-md-12">
				                                    <?php echo $notes['marketing6']['description'];?> 
				                                     </p>
			                  </div>
			                                
			                                
								 <div class="col-md-12 pagination-centered" style="margin-left: 0;">
                                     <div  class="col-lg-4 col-md-4 col-sm-12 col-xs-12 del-padding del-margin" >
                                     	 
				                                  <h3 class="col-md-12 text-left-tablete">
				                                     <i><img src="<?php echo WEB_PATH;?>/public/front/img/Creances.png" class=" icon-martketting re-tkiem-edit"></i>
				                                    <?php echo $notes['marketing7']['title'];?>
				                                  </h3>
				                                    <p class="text-just col-md-12">
				                                    <?php echo $notes['marketing7']['description'];?> 
				                                     </p>
			                               
			                           
                                     </div>
                                     
                                     <div  class="col-lg-8 col-md-8 col-sm-12 col-xs-12  del-padding del-margin" >
                                        <div class="img-mart-02 ">
	                                       <img src="<?php echo WEB_PATH;?>/public/front/img/img-mark-01.png"  class=" img-responsive " style=" width:602px; height:314px;" >
	                                    </div> 
                                      </div>
                                    
                                 </div>
                             

                          </div><!-- class="item active row" -->
                          

                        </div><!-- class="carousel-inner col-md-12" -->
                        

                 

                 
                
            </section>
      </div><!-- id="home-page" class="container content" -->
    </div><!-- id="content" class="container_12" -->
                        
   </div><!-- class="row" -->
</div><!-- class='container' id="giaiphap-ez2" -->
<div class="next"><a href="<?php echo WEB_PATH;?>/product/marketing/marketing3">next</a></div>
<?php die();?>