<?php $notes = $this->notes;
$tr   = new Zend_Translate('ini', LANG_PATH, DEFAULT_LANGUAGE);
?>

 <div class='container' id="giaiphap-maket" >
 	
 	 <div class="row">
                 <div id='page-04-martket-0' >
                      <div class="row height-table-v-012"></div>
                      <!-- col-lg-3 col-md-3 col-sm-12 col-xs-12 animate_afl d1 animate_start -->
                      <div class=" ani row animate_afl d1 animate_start ">
                            <div class="row col-md-12 height-tablebk-page-03">
	                           
	                                  <h3 class="col-md-12 text-lfet-tablete">
	                                    <?php echo $notes['marketing11']['title'];?>
	                                  </h3>
	                                  <p class="text-just col-md-12 ">
	                                       <?php //echo $notes['backoffice1']['description'];?> 
	                                  </p>
	                            
	                           </div><!-- class="col-md-12 del-padding"  -->
	                      
                       </div><!-- end row -->

                      </div><!-- class="row animate_afl d1 animate_start" -->
                
      </div><!-- id='giaiphap' -->
                
 	
 	
    <div class='row  '>
       <div id="content" class="container_12">
     <div id="p-05-martket" class="container content">
                   <!-- Till - block -->

            <section id="till-block" class="row">
                    <div id="slider-app">
                        <div class="col-md-12">
							
                          <div class="item active  row item-doc1 ">
                               
                               <div class="col-md-12 pagination-centered" style="margin-left: 0;">
								  <div class="col-md-4 view-p-mart-04" style="padding-left: 0px;">
	                                  <h3 class="col-md-12 text-h03-tbale">
	                                     <i><img src="<?php echo WEB_PATH;?>/public/front/img/icon-market-05p.png" class=" iconspan6 re-tkiem"></i>
	                                    <?php echo $notes['marketing12']['title'];?>
	                                  </h3>
	                                    <p class="text-just col-md-12">
	                                    <?php echo $notes['marketing12']['description'];?> 
	                                   </p>
	                                     <a href="<?php echo WEB_PATH;?>/register.html">
	                                   <h3 class="  col-md-12 iphone-martk-02 iphone-p-01-mart">
	                                   	<?php echo $tr->translate('btn_sign_up_full');?>
	                                   </h3>
	                                   </a>
                                  </div><!-- view-tanble-07 -->   
                                   
                                  <div class=" col-md-8 view-mart-07" style="padding-right: 5px;">    
		          						 <h3 class="col-md-12 text-h03-tbale">
		                                     <i><img src="<?php echo WEB_PATH;?>/public/front/img/icon-market-05p2.png" class=" iconspan6 re-tkiem"></i>
		                                      <?php echo $notes['marketing13']['title'];?>
		                                   </h3>
                                     <p class="text-just col-md-12">
                                      <?php echo $notes['marketing13']['description'];?> 
                                      </p>
                                      
                                      <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12 padd-l-mart del-padding'>
		                                <div class="img-table-05 animate_afl d2 animate_start">
		                                 <img src="<?php echo WEB_PATH;?>/public/front/img/img-marketing-05p.png"   class="img-responsive" />
	                                    </div>
                                      </div>
                                  </div><!-- view-tanble-07 -->
                                  
								</div>
								
                          </div><!-- class="item active row" -->
                           

                        </div><!-- class="carousel-inner col-md-12" -->
                      
                    </div><!-- id="tillCarousel" class="carousel slide hidden-phone" data-interval="false" -->
                
            </section>
      </div><!-- id="home-page" class="container content" -->
    </div><!-- id="content" class="container_12" -->
                        
   </div><!-- class="row" -->
</div><!-- class='container' id="giaiphap-ez2" -->
<div class="next"><a href="<?php echo WEB_PATH;?>/product/marketing/marketing5">next</a></div>
<?php die();?>