<?php $notes = $this->notes;
$tr   = new Zend_Translate('ini', LANG_PATH, DEFAULT_LANGUAGE);
?>

    <div class='container' id="giaiphap-ez2" >
 
    <div class='row  '>
       <div id="content" class="container_12">
     
      <div id="page-04-02-table-view" class="container content">
                   <!-- Till - block -->

            <section id="till-block" class="row">


                    <div id="slider-app">

                        <div id="tillCarousel" class="carousel slide hidden-phone" data-interval="false">

                        <div class="carousel-inner col-lg-12 col-md-12 col-sm-12 col-xs-12">
							 <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-h3-table">
	                               <?php echo $notes['archive6']['title'];?>
	                         </h3>
	                         
                          <div class="item active  row item-doc1 ">
                               
                                 <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 pagination-centered" style="margin-left: 0;">
								  <div class="view-archi-07-01">
	                                  <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-h03-arch">
	                                     <i><img src="<?php echo WEB_PATH;?>/public/front/img/ul-acr-icon.png" class=" iconspan6 re-tkiem"></i>
	                                    <?php echo $notes['archive7']['title'];?>
	                                  </h3>
	                                    <p class="text-just col-lg-12 col-md-12 col-sm-12 col-xs-12">
	                                    <?php echo $notes['archive7']['description'];?> 
	                                     </p>
                                  </div><!-- view-archi-07 -->   
                                   
                                  <div class="view-archi-07">    
          						 <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-h03-arch">
                                     <i><img src="<?php echo WEB_PATH;?>/public/front/img/ul-acr-icon.png" class=" iconspan6 re-tkiem"></i>
                                      <?php echo $notes['archive8']['title'];?>
                                   </h3>
                                     <p class="text-just col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                      <?php echo $notes['archive8']['description'];?> 
                                      </p>
                                  </div><!-- view-archi-07 -->
                                  
								</div>
								
								 <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 pagination-centered " >
								  <div class="view-archi-07-01">   
                                     <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-h03-arch">
                                     <i><img src="<?php echo WEB_PATH;?>/public/front/img/ul-acr-icon.png" class=" iconspan6 re-tkiem"></i>
                                    <?php echo $notes['archive9']['title'];?>
                                    </h3>
                                    <p class="text-just col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <?php echo $notes['archive9']['description'];?> 
                                     </p>
                                    </div>
                                    
                                     <div class="view-archi-07">   
	          						 <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-h03-arch">
	                                     <i><img src="<?php echo WEB_PATH;?>/public/front/img/ul-acr-icon.png" class=" iconspan6 re-tkiem"></i>
	                                      <?php echo $notes['archive10']['title'];?>
	                                   </h3>
	                                     <p class="text-just col-lg-12 col-md-12 col-sm-12 col-xs-12">
	                                      <?php echo $notes['archive10']['description'];?> 
	                                      </p>
	                                      
	                                  </div>
	                                  
                                  </div>
								
								 <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 pagination-centered" style="margin-left: 0;">
								 
								  <div class="view-archi-07-01">   
                                   <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-h03-arch">
                                     <i><img src="<?php echo WEB_PATH;?>/public/front/img/ul-acr-icon.png" class=" iconspan6 re-tkiem"></i>
                                    <?php echo $notes['archive11']['title'];?>
                                  </h3>
                                    <p class="text-just col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <?php echo $notes['archive11']['description'];?> 
                                     </p>	
                                  </div>
                                     
                                      <div class="view-archi-07">   
		          						 <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-h03-arch">
		                                     <i><img src="<?php echo WEB_PATH;?>/public/front/img/ul-acr-icon.png" class=" iconspan6 re-tkiem"></i>
		                                      <?php echo $notes['archive12']['title'];?>
		                                   </h3>
		                                     <p class="text-just col-lg-12 col-md-12 col-sm-12 col-xs-12">
		                                      <?php echo $notes['archive12']['description'];?> 
		                                      </p>
                                      </div>
                                      
                                  </div>
                                  
                                  
                                  
                                  
                                  
                                  
                                  
                                  
                                  
                                  
                                  
                                   <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 pagination-centered" style="margin-left: 0;">
								  <div class="view-archi-07-02">
	                                  <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-h03-arch">
	                                     <i><img src="<?php echo WEB_PATH;?>/public/front/img/ul-acr-icon.png" class=" iconspan6 re-tkiem"></i>
	                                    <?php echo $notes['archive13']['title'];?>
	                                  </h3>
	                                    <p class="text-just col-lg-12 col-md-12 col-sm-12 col-xs-12">
	                                    <?php echo $notes['archive13']['description'];?> 
	                                     </p>
                                  </div><!-- view-archi-07 -->   
                                  
                                  
								</div>
								
								
								 <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 pagination-centered " >
								  <div class="view-archi-07-02">   
                                     <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-h03-arch">
                                     <i><img src="<?php echo WEB_PATH;?>/public/front/img/ul-acr-icon.png" class=" iconspan6 re-tkiem"></i>
                                    <?php echo $notes['archive14']['title'];?>
                                    </h3>
                                    <p class="text-just col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <?php echo $notes['archive14']['description'];?> 
                                     </p>
                                    </div>
                                    
                                  </div>
                                  
								
								 <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 pagination-centered" style="margin-left: 0;">
								 
								  <div class="view-archi-07-02">   
                                   <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-h03-arch">
                                     <i><img src="<?php echo WEB_PATH;?>/public/front/img/ul-acr-icon.png" class=" iconspan6 re-tkiem"></i>
                                    <?php echo $notes['archive16']['title'];?>
                                  </h3>
                                    <p class="text-just col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <?php echo $notes['archive16']['description'];?> 
                                     </p>	
                                  </div>
                                     
                                 
                                      
                                  </div>
                                 
                               
                                
                                 

                          </div><!-- class="item active row" -->
                           

                        </div><!-- class="carousel-inner col-lg-12 col-md-12 col-sm-12 col-xs-12" -->
                        

                      </div><!-- class="carousel-inner col-lg-12 col-md-12 col-sm-12 col-xs-12" -->

                    </div><!-- id="tillCarousel" class="carousel slide hidden-phone" data-interval="false" -->
                
            </section>
      </div><!-- id="home-page" class="container content" -->
    </div><!-- id="content" class="container_12" -->
                        
   </div><!-- class="row" -->
</div><!-- class='container' id="giaiphap-ez2" -->

  <div class='container' >
          <div class="row">
                 <div id='acr-last' >
                      <div class="row height-view-pro"></div>
                      <!-- col-lg-3 col-md-3 col-sm-12 col-xs-12 animate_afl d1 animate_start -->
                      <div class=" ani row animate_afl d1 animate_start ">
                           
                              <div class="col-md-12 pagination-centered" style="margin-left: 0;">     
                                    <div  class="col-md-3" ></div>
                                     <div  class="col-md-5"><h3 class="iphone-p-acr" style="text-transform: uppercase;">
                                     <a href="<?php echo WEB_PATH;?>/product.html">
                                     <?php echo $tr->translate('btn_review_features');?>
                                     </a>
                                     </h3>
                                     </div>
                                     <div  class="col-md-4" ></div>
                                  </div>

                      </div><!-- class="row animate_afl d1 animate_start" -->
      
                        </div><!-- id='giaiphap' -->
                  </div> <!-- class -row-->
                  
                  
    </div><!-- container-->
    
 <div class='container' >
          <div class="row">
	 <div  class="col-md-12 del-padding del-margin padd-l-mart"  id='acr-next' >
				                                     <div  class="col-lg-4 col-md-4 col-sm-12 col-xs-12" ></div>
				                                     <div  class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
				                                     <a href="<?php echo WEB_PATH;?>/register.html">
				                                     <h3 class="cta-archive-001 padd-l-archive-011">
				                                     <?php echo $tr->translate('btn_sign_up_full');?>
				                                     </h3>
				                                     </a>
				                                     </div>
				                                     <div  class="col-lg-4 col-md-4 col-sm-12 col-xs-12" ></div>
			                                    
	  </div>
  </div> <!-- class -row-->
                  
                  
    </div><!-- container-->
<div class="next"><a href="<?php echo WEB_PATH;?>/product/archive/archive4">next</a></div>
<?php die();?>