<?php $notes = $this->notes;?>
<div class='container' >
        <div class="row">
                 <div id='page-02-acrh' >
                      <div class="row height-table-v-012"></div>
                      <!-- col-lg-3 col-md-3 col-sm-12 col-xs-12 animate_afl d1 animate_start -->
                      <div class=" ani row animate_afl d1 animate_start ">
                            <div class="row col-lg-12 col-md-12 col-sm-12 col-xs-12 height-tablebk-page-03">
	                           
	                               <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 del-padding">
	                               
	                                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 ">
	                                   <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-lfet-tablete">
	                                    <?php echo $notes['archive4']['title'];?>
	                                  </h3>
	                                     <p class="text-just col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
	                                       <?php echo $notes['archive4']['description'];?> 
	                                     </p>
	                                </div>
	                                
	                                <div class='col-lg-6 col-md-6 col-sm-12 col-xs-12  '>
		                                <div class=" animate_afl d2 animate_start img-arch">
		                                 <img src="<?php echo WEB_PATH;?>/public/front/img/DellPOS_Eng.png"   class="img-responsive" />
	                                    </div>
                                      </div>
                                    
	                               </div><!-- class="col-lg-12 col-md-12 col-sm-12 col-xs-12 del-padding"  -->
	                               
	                               
	                                    
	                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 del-padding">
	                               
	                                <div class='col-lg-7 col-md-7 col-sm-12 col-xs-12  page-02-acr-01 '>
	                                 
	                                  
		                              <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12 padd-l-acr del-padding '>
		                                <div class="img-acr-02 animate_afl d2 animate_start">
		                                 <img src="<?php echo WEB_PATH;?>/public/front/img/img-acr-0567.png"   class="img-responsive" />
	                                    </div>
                                      </div>
	                                </div>
	                                
	                                <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12 ">
	                                 <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-acr-1 page-02-acr-01">
	                                  
	                                    <?php echo $notes['archive5']['title'];?>
	                                  </h3>
	                                     <p class="text-just col-lg-12 col-md-12 col-sm-12 col-xs-12  padd-acr-02">
	                                       <?php echo $notes['archive5']['description'];?> 
	                                     </p>
	                                </div>
	                                
	                              
	                               </div><!-- class="col-lg-12 col-md-12 col-sm-12 col-xs-12 del-padding"  -->
                             
                                
                            </div><!-- end row -->

                      </div><!-- class="row animate_afl d1 animate_start" -->
                     


                        </div><!-- id='giaiphap' -->
            </div> <!-- class -row-->
    </div><!-- container-->
    
<div class="next"><a href="<?php echo WEB_PATH;?>/product/archive/archive3">next</a></div>
<?php die();?>