<?php $notes = $this->notes;?>
<div class='container' >
          <div class="row">
                 <div id='page-bg_tele' >
                      <div class="row height-view-pro"></div>
                      <!-- col-lg-3 col-md-3 col-sm-12 col-xs-12 animate_afl d1 animate_start -->
                      <div class=" ani row animate_afl d1 animate_start ">
                            <div class="row ">
                                <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12 gp-h3-teleche'>
                                     <?php // echo $notes['archive0']['title'];?>
                                </div>
                              
                            </div><!-- end row -->

                      </div><!-- class="row animate_afl d1 animate_start" -->
                     


                        </div><!-- id='giaiphap' -->
                  </div> <!-- class -row-->
    </div><!-- container-->
    <div class='container' id="page-01-archive-of-hei" >
 
    <div class='row  '>
       <div id="content" class="container_12">
            

      <div id="page-03-teleche-01" class="container content">
                   <!-- Till - block -->

            <section id="till-block" class="row">

                        <div class="col-md-12">

                          <div class="item active  row page01-bkooffice " >
                               
								 <div class="col-md-12 pagination-centered" >
								      <div class="col-md-12">
								        <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-h03-arch">
	                                     <i><img src="<?php echo WEB_PATH;?>/public/front/img/icon-download-010.png" class=" iconspan6 re-tkiem"></i>
	                                      <?php echo $notes['telecharger5']['title'];?>
	                                    </h3>
	                                    <div class=" row col-lg-12 col-md-12 col-sm-12 col-xs-12">
		                                    <p class="text-just col-lg-6 col-md-6 col-sm-12 col-xs-12">
		                                    <?php echo $notes['telecharger5']['description'];?> 
		                                     </p>
	                                    </div>
	                                    
								      </div>
                                      <div  class=" col-lg-12 col-md-12 col-sm-12 col-xs-12  img-mart del-padding del-margin" >
	                                      <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12"></div>
		                                  <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
		                                    <img src="<?php echo WEB_PATH;?>/public/front/img/img-download-10.png"  class=" img-responsive " style="padding-left: 0%;width:317px; height:522px;" >
		                                  </div> 
		                                  <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12"></div>
	                                  
                                      </div>
                                      
                                    
                                 </div>
                                
			             

                          </div><!-- class="item active row" -->
                          

                        </div><!-- class="carousel-inner col-md-12" -->
             
            </section>
      </div><!-- id="home-page" class="container content" -->
      
    </div><!-- id="content" class="container_12" -->
        <?php /* ?> 
       <div id="telechar-03-01">                   
				            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" >
				              <p class="col-lg-12 col-md-12 col-sm-12 col-xs-12 h3-telechevie" >
				              Attention
				               </p>
				               <span class="text-ul-prix col-lg-11 col-md-11 col-sm-11 col-xs-12">
				              
									(1) Le tarif est compté par mois.
							 
							   	(2) Le paquet de chaine de magasins fournit des fonctions spécifiques qui satisfont les besoins de franchise.
							 
									(3) Le paquet de chaine de magasins est applique pour les chaines de 5 magasins. Plus de 5 magasins, 
									veuillez nous contacter par Hotline.
							  		
				               
				               </span>
								
				            </div>      
						</div><!-- id="prix-gd-02" -->        
			<?php */ ?>            
   </div><!-- class="row" -->
</div><!-- class='container' id="giaiphap-ez2" -->
<div class="next"><a href="<?php echo WEB_PATH;?>/telecharger/index/telecharger4">next</a></div>
<?php die();?>