<div class='login-container-footer' style="background-color: #00ACEC;">
            <div class='container'>
              <div class='row'>
                <div class='col-sm-12'>
                  <div class='text-center'>
                    <a href='sign_up.html'>
                      Copyright © Playboy Viet
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
