<?php $notes = $this->notes;
$tr   = new Zend_Translate('ini', LANG_PATH, DEFAULT_LANGUAGE);
?>
<div class="bg-ogg-fficw">
<div class='container' >
   </div><!-- container-->
    <div class='container' id="bg-office-05" >
 
    <div class='row  '>
       <div id="content" class="container_12">
            

      <div id="home-page" class="container content">
                   <!-- Till - block -->

            <section id="till-block" class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

                          <div class="item active  row  ">
                             
                                 <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 pagination-smart03" >
                                   <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12 h3-bkoffice-05  animate_afl d1 animate_start ">
                                    <?php echo $notes['backoffice10']['title'];?>
                                   </h3>
								   <p class="text-bk-ofi-05 col-lg-12 col-md-12 col-sm-12 col-xs-12  animate_afl d2 animate_start" style="font-size: 16px;">
								   
								    <?php echo $notes['backoffice10']['description'];?> 
                                   </p>
          							
          						 <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          						 	
          							<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12" >
	                                   <ul class="bk-office-05-ul text-bk-ofi-05 animate_afl d4 animate_start">
	                                   <li><img src="<?php echo WEB_PATH;?>/public/front/img/bl-list-office-05.png" class="img-li-bk-office-05">Interface for retail store</li>
	                                   <li><img src="<?php echo WEB_PATH;?>/public/front/img/bl-list-office-05.png" class="img-li-bk-office-05">Interface for coffee shop</li>
	                                   </ul>
                                     </div>
                                     
                                     <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12" >
	                                    <ul class="bk-office-05-ul text-bk-ofi-05 animate_afl d3 animate_start">
		                                   <li><img src="<?php echo WEB_PATH;?>/public/front/img/bl-list-office-05.png" class="img-li-bk-office-05">Interface for restaurant</li>
		                                   <li><img src="<?php echo WEB_PATH;?>/public/front/img/bl-list-office-05.png" class="img-li-bk-office-05">Interface for supermarket</li>
	                                   </ul>
                                     </div>
                                     
          							 <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12" >
          							 <a href="<?php echo WEB_PATH;?>/register.html">
	                                    <h3 class="iphone-view-smartphone-05  animate_afl d6 animate_start">
	                                     <?php echo $tr->translate('btn_sign_up_full');?> 
	                                    
	                                    </h3>
	                                   </a> 
                                     </div>
                                 </div>
                                     
                                </div>
                     </div><!-- class="item active row" -->
         </section>
      </div><!-- id="home-page" class="container content" -->
    </div><!-- id="content" class="container_12" -->
                        
   </div><!-- class="row" -->
  </div><!-- class='container' id="giaiphap-ez2" -->
</div><!-- report-bc -->
<div class="next"><a href="<?php echo WEB_PATH;?>/product/backoffice/backoffice6">next</a></div>
<?php die();?>    