<?php $notes = $this->notes;?>

    <div class='container' id="" >
 
    <div class='row  '>
       <div id="content" class="container_12">
            

      <div id="home-page" class="container content">
                   <!-- Till - block -->

            <section id="till-block" class="row">


                    <div id="slider-app">

                        <div id="tillCarousel" class="carousel slide hidden-phone" data-interval="false">

                        <div class="carousel-inner col-md-12">

                          <div class="item active  row item-doc1">
                               
                                 <div class="col-md-4 pagination-centered" style="margin-left: 0;">
								  <div class="view-0ffice-07">
	                                  <h3 class="col-md-12 text-left-backoffice">
	                                     <i><img src="<?php echo WEB_PATH;?>/public/front/img/icon-bk-of-01.png" class=" iconspan6 re-tkiem"></i>
	                                    <?php echo $notes['backoffice4']['title'];?>
	                                  </h3>
	                                    <p class="text-just col-md-12">
	                                    <?php echo $notes['backoffice4']['description'];?> 
	                                     </p>
                                  </div><!-- view-0ffice-07 -->   
                                   
                                  <div class="view-0ffice-07">    
          						 <h3 class="col-md-12 text-left-backoffice">
                                     <i><img src="<?php echo WEB_PATH;?>/public/front/img/icon-bk-of-06.png" class=" iconspan6 re-tkiem"></i>
                                      <?php echo $notes['backoffice5']['title'];?>
                                   </h3>
                                     <p class="text-just col-md-12">
                                      <?php echo $notes['backoffice5']['description'];?> 
                                      </p>
                                  </div><!-- view-0ffice-07 -->
                                  
								</div>
								
								 <div class="col-md-4 pagination-centered " >
								  <div class="view-0ffice-07">   
                                     <h3 class="col-md-12 text-left-backoffice">
                                     <i><img src="<?php echo WEB_PATH;?>/public/front/img/icon-bk-of-02.png" class=" iconspan6 re-tkiem"></i>
                                    <?php echo $notes['backoffice2']['title'];?>
                                    </h3>
                                    <p class="text-just col-md-12">
                                    <?php echo $notes['backoffice2']['description'];?> 
                                     </p>
                                    </div>
                                    
                                     <div class="view-0ffice-07">   
	          						 <h3 class="col-md-12 text-left-backoffice">
	                                     <i><img src="<?php echo WEB_PATH;?>/public/front/img/icon-bk-of-05.png" class=" iconspan6 re-tkiem"></i>
	                                      <?php echo $notes['backoffice7']['title'];?>
	                                   </h3>
	                                     <p class="text-just col-md-12">
	                                      <?php echo $notes['backoffice7']['description'];?> 
	                                      </p>
	                                      
	                                  </div>
	                                  
                                  </div>
								
								 <div class="col-md-4 pagination-centered" style="margin-left: 0;">
								 
								  <div class="view-0ffice-07">   
                                   <h3 class="col-md-12 text-left-backoffice">
                                     <i><img src="<?php echo WEB_PATH;?>/public/front/img/icon-bk-of-03.png" class=" iconspan6 re-tkiem"></i>
                                    <?php echo $notes['backoffice3']['title'];?>
                                  </h3>
                                    <p class="text-just col-md-12">
                                    <?php echo $notes['backoffice3']['description'];?> 
                                     </p>	
                                     </div>
                                     
                                      <div class="view-0ffice-07">   
		          						 <h3 class="col-md-12 text-left-backoffice">
		                                     <i><img src="<?php echo WEB_PATH;?>/public/front/img/icon-bk-of-04.png" class=" iconspan6 re-tkiem"></i>
		                                      <?php echo $notes['backoffice6']['title'];?>
		                                   </h3>
		                                     <p class="text-just col-md-12">
		                                      <?php echo $notes['backoffice6']['description'];?> 
		                                      </p>
                                      </div>
                                      
                                  </div>
                                 
                               
                                
                                 

                          </div><!-- class="item active row" -->
                           <div class="item   row item-doc1 hieght-pad"></div>
                           <div class="item   row item-doc1 hieght-pad"></div>

                        </div><!-- class="carousel-inner col-md-12" -->
                        

                      </div><!-- class="carousel-inner col-md-12" -->

                    </div><!-- id="tillCarousel" class="carousel slide hidden-phone" data-interval="false" -->
                
            </section>
      </div><!-- id="home-page" class="container content" -->
    </div><!-- id="content" class="container_12" -->
                        
   </div><!-- class="row" -->
</div><!-- class='container' id="giaiphap-ez2" -->
<div class="next"><a href="<?php echo WEB_PATH;?>/product/backoffice/backoffice4">next</a></div>
<?php die();?>