<?php $notes = $this->notes;
$tr   = new Zend_Translate('ini', LANG_PATH, DEFAULT_LANGUAGE);
?>
<div class='container' >
          <div class="row">
                 <div id='giaiphap-ez1-prod' >
                      <div class="row height-view-pro"></div>
                      <!-- col-lg-3 col-md-3 col-sm-12 col-xs-12 animate_afl d1 animate_start -->
                      <div class=" ani row animate_afl d1 animate_start ">
                            <div class="row ">
                                <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12 giaiphap'></div>
                                <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12' id='title_khachhang'>
                                 <?php echo $tr->translate('txt_title_config_simple_backof');?> 
                                </div>
                               
                            </div><!-- end row -->

                      </div><!-- class="row animate_afl d1 animate_start" -->
                     


                        </div><!-- id='giaiphap' -->
                  </div> <!-- class -row-->
    </div><!-- container-->
    <div class='container' id="giaiphap-product" >
 
    <div class='row  '>
       <div id="content" class="container_12">
            

      <div id="home-page" class="container content">
                   <!-- Till - block -->

            <section id="till-block" class="row">


                    <div id="slider-app">

                        <div id="tillCarousel" class="carousel slide hidden-phone" data-interval="false">

                        <div class="carousel-inner col-md-12">
							<div class="item  active  row page-office-04">
                             <h3 class="col-md-12 text-bkoff">
                             <?php echo $notes['backoffice8']['title'];?>
                             </h3>
                                    <p class="text-just-bk col-md-12">
                                        <?php echo $notes['backoffice8']['description'];?> 
                                    </p>
                             </div>
                             <div class="item active  row item-doc1 ">
                              
                                 <div class="col-md-6 pagination-centered" style="margin-left: 0;">
								 
							      <h3 class="col-md-12 text-smartp">
							        <?php echo $notes['backoffice9']['title'];?>
							      </h3>
                                    <p class="text-just col-md-12">
                                    <?php echo $notes['backoffice9']['description'];?> 
                                    </p>
                                   
                                    <ul class="ul-bk-ofi-04 col-md-12 animate_afl d4 animate_start ">
                                    	<li ><img src="<?php echo WEB_PATH;?>/public/front/img/img-bk-of-04.png" class="img-li-bkofii-office-04 ">
                                    	 <?php echo $tr->translate('txt_backof_1');?> 
                                    	</li>
                                    	<li><img src="<?php echo WEB_PATH;?>/public/front/img/img-bk-of-04.png" class="img-li-bkofii-office-04 ">
                                    	 <?php echo $tr->translate('txt_backof_2');?> 
                                    	</li>
                                    	<li><img src="<?php echo WEB_PATH;?>/public/front/img/img-bk-of-04.png" class="img-li-bkofii-office-04 ">
                                    	 <?php echo $tr->translate('txt_backof_3');?> 
                                    	</li>
                                    	<li ><img src="<?php echo WEB_PATH;?>/public/front/img/img-bk-of-04.png" class="img-li-bkofii-office-04 ">
                                    	 <?php echo $tr->translate('txt_backof_4');?> 
                                    	</li>
                                    	<li ><img src="<?php echo WEB_PATH;?>/public/front/img/img-bk-of-04.png" class="img-li-bkofii-office-04">
                                    	 <?php echo $tr->translate('txt_backof_5');?> 
                                    	</li>
                                    	<li><img src="<?php echo WEB_PATH;?>/public/front/img/img-bk-of-04.png" class="img-li-bkofii-office-04">
                                    	 <?php echo $tr->translate('txt_backof_6');?> 
                                    	</li>
                                    	<li ><img src="<?php echo WEB_PATH;?>/public/front/img/img-bk-of-04.png" class="img-li-bkofii-office-04">
                                     	<?php echo $tr->translate('txt_backof_7');?> 
                                    	</li>
                                    	<li ><img src="<?php echo WEB_PATH;?>/public/front/img/img-bk-of-04.png" class="img-li-bkofii-office-04">
                                     	<?php echo $tr->translate('txt_backof_8');?> 
                                    	</li>
                                    </ul>
                                   
                                      
                               
                                  </div>
                                 
                                  
                                   <div class="col-md-6 pagination-centered" style="margin-left: 0;">
                                     <img src="<?php echo WEB_PATH;?>/public/front/img/baocao_Eg_iPhone.png" alt="caisse enregistreuse caltos"  class="img-responsive col-md-12 animate_afl d2 animate_start" style="width: 100%; max-width:467px ; height:459px ;margin-top: -1%;">
	                                 
                                   </div>
                                
                           

                          </div><!-- class="item active row" -->
                           
                          

                        </div><!-- class="carousel-inner col-md-12" -->
                        

                      </div><!-- class="carousel-inner col-md-12" -->

                    </div><!-- id="tillCarousel" class="carousel slide hidden-phone" data-interval="false" -->
                
            </section>
      </div><!-- id="home-page" class="container content" -->
    </div><!-- id="content" class="container_12" -->
                        
   </div><!-- class="row" -->
</div><!-- class='container' id="giaiphap-ez2" -->
<div class="next"><a href="<?php echo WEB_PATH;?>/product/backoffice/backoffice5">next</a></div>
<?php die();?>