<?php $notes = $this->notes;?>
   <div class='container' style="padding-top: 20px;" >
          <div class="row">
                 <div id='giaiphap-pag1-prod' >
                      <div class="row height-view-pro"></div>
                      <!-- col-lg-3 col-md-3 col-sm-12 col-xs-12 animate_afl d1 animate_start -->
                      <div class=" ani row animate_afl d1 animate_start ">
                            <div class="row col-md-12 height-bk-page-03">
	                            <div class="col-md-8">
	                                  <h3 class="col-md-12 text-left-backoffice" style="font-size: 32px;color: #4e4e4e;">
	                                    <?php echo $notes['backoffice1']['title'];?>
	                                  </h3>
	                                    <p class="text-just col-md-12">
	                                    <?php echo $notes['backoffice1']['description'];?> 
	                                     </p>
	                              </div>
                              
                                 <div class='col-lg-4 col-md-4 col-sm-12 col-xs-12 '>
                                  <img src="<?php echo WEB_PATH;?>/public/front/img/01baocao_Eng.png"   class="col-md-12 animate_afl d2 animate_start" style="width: 100%;max-width: 380px;height: 228px;padding: 0px;margin: 0px;"> 
                                 </div>
                            </div><!-- end row -->

                      </div><!-- class="row animate_afl d1 animate_start" -->
                     


                        </div><!-- id='giaiphap' -->
                  </div> <!-- class -row-->
    </div><!-- container-->

<div class="next"><a href="<?php echo WEB_PATH;?>/product/backoffice/backoffice3">next</a></div>
<?php die();?>