<?php $notes = $this->notes;
$tr   = new Zend_Translate('ini', LANG_PATH, DEFAULT_LANGUAGE);
?>
<div class='container'>
    <div class="row">
         <div id='bg-backoffice-ul-li' class="animate_afb d1 animate_start" >
           <div class='col-lg-3 col-md-3 col-sm-3 col-xs-12 ul-prix-ul-right-07-bk'>
                <div class="cn-wrapper">
	              <ul class="nav nav-list nav-el-ez">
	                <li class="nav-header circle"><a href="#"><i class="icon-Vente"></i>	 <?php echo $tr->translate('txt_menu_right_store');?> </a></li>
	                <li class="nav-header circle active-navul"><a href="#"><i class="icon-Gestion"></i><?php echo $tr->translate('txt_menu_right_inventory');?></a></li>
	                <li class="nav-header circle "><a href="#"><i class="icon-clients"></i><?php echo $tr->translate('txt_menu_right_debts');?></a></li>
	                <li class="nav-header circle "><a href="#"><i class="icon-Employ"></i><?php echo $tr->translate('txt_menu_right_employee');?></a></li>
	                <li class="nav-header circle "><a href="#"><i class="icon-ser-Clients"></i><?php echo $tr->translate('txt_menu_right_customer');?></a></li>
	                <li class="nav-header circle "><a href="#"><i class="icon-Promotions"></i><?php echo $tr->translate('txt_menu_right_promotions');?></a></li>
	                <li class="nav-header circle "><a href="#"><i class="icon-Chanedemagasins"></i><?php echo $tr->translate('txt_menu_right_multi_store');?></a></li>
	                <li class="nav-header circle "><a href="#"><i class="icon-Rapports"></i><?php echo $tr->translate('txt_menu_right_reports');?></a></li>
	              </ul>
			 </div>
            </div><!-- class='span3' -->
            
            
             <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12 ul-left-07" >
              <div id="cn-tabs">
                   <div class="service service-1">
                        <div class="cn-content" id="active-ct">
				              <h3 class="col-md-11 text-h3-prix-03"><i><img src="<?php echo WEB_PATH;?>/public/front/img/icon/config.png" class=" iconspan6-product re-tkiem"></i>  
				                <?php echo $notes['backoffice12']['title'];?>             
				              </h3>
				              <p class="text-just col-md-12">
				                <?php echo $notes['backoffice12']['description'];?> 
				              </p>
				       </div>
				      </div>
				    </div>
				    
				  <div id="cn-tabs">
                   <div class="service service-2">
                        <div class="cn-content">
		              <h3 class="col-md-11 text-h3-prix-03"><i><img src="<?php echo WEB_PATH;?>/public/front/img/icon/iventory.png" class=" iconspan6-product re-tkiem"></i>  
		                <?php echo $notes['backoffice11']['title'];?>         
		              </h3>
		              <p class="text-just col-md-12">
		                 <?php echo $notes['backoffice11']['description'];?> 
		              </p>
		              </div>
				      </div>
				    </div>
				
				
				 <div id="cn-tabs">
                   <div class="service service-3">
                        <div class="cn-content">
		              <h3 class="col-md-11 text-h3-prix-03"><i><img src="<?php echo WEB_PATH;?>/public/front/img/icon/debts.png" class=" iconspan6-product re-tkiem"></i>  
		                <?php echo $notes['backoffice13']['title'];?>  
		              </h3>
		              <p class="text-just col-md-12">
		                <?php echo $notes['backoffice13']['description'];?> 
		              </p>
		              </div>
				      </div>
				    </div>
				    
				    
				    
				    
				     <div id="cn-tabs">
                   <div class="service service-4">
                        <div class="cn-content">
		              <h3 class="col-md-11 text-h3-prix-03"><i><img src="<?php echo WEB_PATH;?>/public/front/img/icon/employee.png" class=" iconspan6-product re-tkiem"></i>  
		                <?php echo $notes['backoffice14']['title'];?>           
		              </h3>
		              <p class="text-just col-md-12">
		               <?php echo $notes['backoffice14']['description'];?> 
		              </p>
		              </div>
				      </div>
				    </div>    
				    
				    
				    
				    
				    
				     <div id="cn-tabs">
                   <div class="service service-5">
                        <div class="cn-content">
		              <h3 class="col-md-11 text-h3-prix-03"><i><img src="<?php echo WEB_PATH;?>/public/front/img/icon/customer.png" class=" iconspan6-product re-tkiem"></i>  
		                <?php echo $notes['backoffice15']['title'];?>    
		              </h3>
		              <p class="text-just col-md-12">
		               <?php echo $notes['backoffice15']['description'];?>
		              </p>
		              </div>
				      </div>
				    </div>
				    
				    
				     <div id="cn-tabs">
                   <div class="service service-6">
                        <div class="cn-content">
		              <h3 class="col-md-11 text-h3-prix-03"><i><img src="<?php echo WEB_PATH;?>/public/front/img/icon/promotions.png" class=" iconspan6-product re-tkiem"></i>  
		                <?php echo $notes['backoffice16']['title'];?>          
		              </h3>
		              <p class="text-just col-md-12">
		                 <?php echo $notes['backoffice16']['description'];?>
		              </p>
		              </div>
				      </div>
				    </div>
				    
				    
				    
				     <div id="cn-tabs">
                   <div class="service service-7">
                        <div class="cn-content">
		              <h3 class="col-md-11 text-h3-prix-03"><i><img src="<?php echo WEB_PATH;?>/public/front/img/icon/multistore.png" class=" iconspan6-product re-tkiem"></i>  
		                 <?php echo $notes['backoffice17']['title'];?>           
		              </h3>
		              <p class="text-just col-md-12">
		                <?php echo $notes['backoffice17']['description'];?>
		              </p>
		              </div>
				      </div>
				    </div>
				    
				    
				    
				    
				     <div id="cn-tabs">
                   <div class="service service-8">
                        <div class="cn-content">
		              <h3 class="col-md-11 text-h3-prix-03"><i><img src="<?php echo WEB_PATH;?>/public/front/img/icon/resport.png" class=" iconspan6-product re-tkiem"></i>  
		                <?php echo $notes['backoffice18']['title'];?>                
		              </h3>
		              <p class="text-just col-md-12">
		                 <?php echo $notes['backoffice18']['description'];?>
		              </p>
		              </div>
				      </div>
				    </div>
             </div><!-- class="span8" -->
             <div class='container' >
             
          <div class="row">
                 <div id='acr-last' >
                      <div class="row height-view-pro"></div>
                      <br><br>
                      <!-- col-lg-3 col-md-3 col-sm-12 col-xs-12 animate_afl d1 animate_start -->
                      <div class=" ani row animate_afl d1 animate_start ">
                           
                              <div class="col-md-12 pagination-centered" style="margin-left: 0;">     
                                    <div  class="col-md-3" ></div>
                                     <div  class="col-md-5"><h3 class="iphone-p-acr" style="text-transform: uppercase;">
                                     <a href="<?php echo WEB_PATH;?>/product.html">
                                     <?php echo $tr->translate('btn_review_features');?>
                                     </a>
                                     </h3>
                                     </div>
                                     <div  class="col-md-4" ></div>
                                  </div>

                      </div><!-- class="row animate_afl d1 animate_start" -->
      
                        </div><!-- id='giaiphap' -->
                  </div> <!-- class -row-->
    </div><!-- container-->
    
 <div class='container' >
          <div class="row">
	 <div  class="col-md-12 del-padding del-margin padd-l-mart"  id='acr-next' >
				                                     <div  class="col-lg-4 col-md-4 col-sm-12 col-xs-12" ></div>
				                                     <div  class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
				                                     <a href="<?php echo WEB_PATH;?>/register.html">
				                                     <h3 class="cta-archive-001 padd-l-archive-011">
				                                     <?php echo $tr->translate('btn_sign_up_full');?>
				                                     </h3>
				                                     </a>
				                                     </div>
				                                     <div  class="col-lg-4 col-md-4 col-sm-12 col-xs-12" ></div>
			                                    
	  </div>
  </div> <!-- class -row-->
    </div>
        </div><!-- sanpham-->   
    </div><!-- class="row" -->
    </div><!-- container-->
    
    <script >
		  
		     $( document ).ready(function() {
			    	 $('li.circle').hover(function(){ 
			    		var c = $(this).index() +1;
			    		var j = ".service-" + c + " .cn-content";
			    		var k = ".service-" + c;
	
			    		$(".service").hide(); 
			    		$(k).show().stop(); 
	
			    		$(".cn-content").animate({ "opacity": 0 }, 300, 'easeInOutCubic'); 
			    			$(j).animate({ "opacity": 1 }, 400, 'easeInOutCubic').stop(); 
	
			    	});
	
	
	
			    	$(".service-1").animate(500, 'easeInOutCubic').show(); 
			    	$(".service-1 .cn-content").animate({ "opacity": 1 }, 400, 'easeInOutCubic'); 
			    		
			    	$('.cn-wrapper li a').hover(function() {
			    		     $('.cn-wrapper li').removeClass('active-navul');
			    			 $(this).parent().addClass('active-navul');
			    	})
		     
		    });
     </script>
<div class="next"><a href="<?php echo WEB_PATH;?>/product/backoffice/backoffice7">next</a></div>
<?php die();?>    