<?php $notes = $this->notes;?>
<div class='container' >
          <div class="row">
                 <div id='giaiphap-ez1-prod' >
                      <div class="row height-view-pro"></div>
                      <!-- col-lg-3 col-md-3 col-sm-12 col-xs-12 animate_afl d1 animate_start -->
                      <div class=" ani row animate_afl d1 animate_start ">
                            <div class="row ">
                            <!--  
                                <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12 giaiphap'></div>
                                <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12' id='title_khachhang'><?php echo $notes['hardware5']['title'];?></div>
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id='_contect_khachhang'>
                                  <p class="p-view-ttkh ">
                                   <?php echo $notes['hardware5']['description'];?>  
                                  </p>
                                </div>
                             -->  
                            </div><!-- end row -->

                      </div><!-- class="row animate_afl d1 animate_start" -->
                     


                        </div><!-- id='giaiphap' -->
                  </div> <!-- class -row-->
    </div><!-- container-->
    <div class='container' id="giaiphap-product" >
 
    <div class='row  '>
       <div id="content" class="container_12">
            

      <div id="home-page" class="container content">
                   <!-- Till - block -->

            <section id="till-block" class="row">


                    <div id="slider-app">

                        <div id="tillCarousel" class="carousel slide hidden-phone" data-interval="false">

                         <div class="carousel-inner col-md-12">

                          <div class="item active  row item-doc1 hieght-pad">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" >
								   <div class="col-lg-7 col-md-7 col-sm-12 col-xs-12"> 
                                  <h3 class="col-md-12 text-left99-product"><i><img src="<?php echo WEB_PATH;?>/public/front/img/icon-phancung-Eng_01.png" class=" iconspan6-product re-tkiem"></i>  
                                  <?php echo $notes['hardware9']['title'];?>
                                  </h3>
                                    <p class="text-just col-md-11"> <?php echo $notes['hardware9']['description'];?>  </p>
                                 </div>
                                     
                                     <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12">
                                       <img src="<?php echo WEB_PATH;?>/public/front/img/img-phancung-Eng_01.png" alt="caisse enregistreuse caltos"  class="" style="max-width: 399px;margin-bottom: 0%;height: 255px;">
                                    </div>
                                     
                            </div>
                            
                             <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" >
								   <div class="col-lg-7 col-md-7 col-sm-12 col-xs-12"> 
                                  <h3 class="col-md-12 text-left99-product"><i><img src="<?php echo WEB_PATH;?>/public/front/img/icon-hardw-04.png" class=" iconspan6-product re-tkiem"></i> 
                                   <?php echo $notes['hardware6']['title'];?>
                                   </h3>
                                    <p class="text-just col-md-11"> <?php echo $notes['hardware6']['description'];?>  </p>
                                 </div>
                                     
                                     <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12">
                                       <img src="<?php echo WEB_PATH;?>/public/front/img/img-phancung-Eng_02.png" alt="caisse enregistreuse caltos"  class="" style="max-width: 265px;margin-bottom: 1%;height: 296px;">
                                    </div>
                                     
                            </div>  
                            
                               
                            
                          </div><!-- class="item active row" -->
                          

                        </div><!-- class="carousel-inner col-md-12" -->
                        

                      </div><!-- class="carousel-inner col-md-12" -->

                    </div><!-- id="tillCarousel" class="carousel slide hidden-phone" data-interval="false" -->
                
            </section>
      </div><!-- id="home-page" class="container content" -->
    </div><!-- id="content" class="container_12" -->
                        
   </div><!-- class="row" -->
</div><!-- class='container' id="giaiphap-ez2" -->

<div class="next"><a href="<?php echo WEB_PATH;?>/hardware/index/hardware3">next</a></div>
<?php die();?>