<?php $notes = $this->notes;
//echo $this->action('slider','elements','front');
?>

     <div class="scroll" data-ui="jscroll-default">
     <div class='container' >
          <div class="row">
                 <div id='giaiphap-pag1-prod' >
                      <div class="row height-view-pro"></div>
                      <!-- col-lg-3 col-md-3 col-sm-12 col-xs-12 animate_afl d1 animate_start -->
                      <div class=" ani row animate_afl d1 animate_start ">
                      <br><br>
                            <div class="row ">
                              
                                <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12' id='title_hardware-01'>
                                  <?php echo $notes['hardware0']['title'];?> 
                                </div>
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id='_contect_khachhang'>
                                  <p class="p-view-ttkh-har ">
                                    <?php echo $notes['hardware0']['description']?>
                                    </p>
                                </div>
                               
                            </div><!-- end row -->

                      </div><!-- class="row animate_afl d1 animate_start" -->
                     


                        </div><!-- id='giaiphap' -->
                  </div> <!-- class -row-->
    </div><!-- container-->
    <div class='container' id="giaiphap-ez2" >
 
    <div class='row  '>
       <div id="content" class="container_12">
            

      <div id="home-page" class="container content">
                   <!-- Till - block -->

            <section id="till-block" class="row">


                    <div id="slider-app">

                        <div id="tillCarousel" class="carousel slide hidden-phone" data-interval="false">

                        <div class="carousel-inner col-md-12">

                          <div class="item active  row item-doc1 hieght-pad">
                               
                            <div class=" pagination-centered" style="margin-left: 0;">
                                 
								 <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" >
								 
								    <div class="col-lg-7 col-md-7 col-sm-12 col-xs-12">
	                                  <h3 class="col-md-11 text-left-product">
	                                      <i>
	                                      <img src="<?php echo WEB_PATH;?>/public/front/img/icon-hardw-01.png" class=" iconspan6-product re-tkiem">
	                                      </i>
	                                      <?php echo $notes['hardware1']['title'];?>
	                                  </h3>
	                                    <p class="text-just-harw col-md-11">
	                                      <?php echo $notes['hardware1']['description'];?> 
	                                     </p>
                                     </div>
                                     
                                     <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12">
                                       <img src="<?php echo WEB_PATH;?>/public/front/img/img-hardw-01.png" alt="caisse enregistreuse caltos"  class="" style="max-width: 310px;margin-bottom: 1%;height: 289px;">
                                    </div>
                                   
                                  </div>   
          
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" >
                                	  <div class="col-lg-7 col-md-7 col-sm-12 col-xs-12"> 
			                                 <h3 class="col-md-11 text-left-product"><i><img src="<?php echo WEB_PATH;?>/public/front/img/icon-hardw-02.png" class=" iconspan6-product re-tkiem"></i>
			                                 <?php echo $notes['hardware2']['title'];?></h3>
			                                    <p class="text-just-harw col-md-11">
			                                     <?php echo $notes['hardware2']['description'];?> 
			                                    </p>
                                       </div>
                                     
                                     <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12">
                                       <img src="<?php echo WEB_PATH;?>/public/front/img/img-hardw-02.png" alt="caisse enregistreuse caltos"  class="" style="max-width: 299px;margin-bottom: 1%;height: 255px;">
                                     </div>
                                     
                                  </div>
                                    
                                    
                              	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" >
                              	   <div class="col-lg-7 col-md-7 col-sm-12 col-xs-12">      
		                                <h3 class='h3-span-pro'>
		                                <i><img src="<?php echo WEB_PATH;?>/public/front/img/icon-hardw-03.png" class=" iconspan6-product re-tkiem"></i>
		                               <?php echo $notes['hardware3']['title'];?>
		                               </h3>
		                                <p class='text-just-harw col-md-11'> <?php echo $notes['hardware3']['description'];?>  
		                                 </p>
                                     </div>
                                     
                                     <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12">
                                       <img src="<?php echo WEB_PATH;?>/public/front/img/img-hardw-03.png" alt="caisse enregistreuse caltos"  class="" style="max-width: 391px;margin-bottom: 1%;height: 218px;">
                                    </div>
                                     
                                </div>
                                
                                
                                        
                              	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" > 
		                               <h3 class='h3-span-hard-099 col-lg-12 col-md-12 col-sm-12 col-xs-12'><?php echo $notes['hardware4']['title'];?></h3>
		                                 <p class="text-just-harw col-md-11">
		                                    <?php echo $notes['hardware4']['description'];?>  
		                                 </p>
                               </div>
                                
                             </div>     

                          </div><!-- class="item active row" -->
                          

                        </div><!-- class="carousel-inner col-md-12" -->
                        

                      </div><!-- class="carousel-inner col-md-12" -->

                    </div><!-- id="tillCarousel" class="carousel slide hidden-phone" data-interval="false" -->
                
            </section>
      </div><!-- id="home-page" class="container content" -->
    </div><!-- id="content" class="container_12" -->
                        
   </div><!-- class="row" -->
</div><!-- class='container' id="giaiphap-ez2" -->
<a href="<?php echo WEB_PATH;?>/hardware/index/hardware2">next</a>
      </div>
      <script>
      $('.scroll').jscroll();
      </script>

