<?php $tr   = new Zend_Translate('ini', LANG_PATH, DEFAULT_LANGUAGE);?>
<div class='container'>
    <div class="row">
         <div id='sanpham' >
             <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12 "><!-- fix-imges -->
              <img src="<?php echo WEB_PATH;?>/public/front/img/imgae-bg-tinhnang.png" class="img-responsive img-fix-span8" >
            </div><!-- class="span8" -->

            <div class='col-lg-3 col-md-3 col-sm-3 col-xs-12 ul-right-ez3'>
              <ul class="nav nav-list nav-el-ez">
                <li class="nav-header active-navul"><a href="<?php echo WEB_PATH;?>/register.html"><i class="icon-cloud"></i><?php echo $tr->translate('txt_menu_right_sign_in');?> </a></li>
                <li class="nav-header"><a href="<?php echo WEB_PATH;?>/product/backoffice"><i class="icon-Vente"></i><?php echo $tr->translate('txt_menu_right_store');?> </a></li>
                <li class="nav-header"><a href="<?php echo WEB_PATH;?>/product/backoffice"><i class="icon-Vente-2"></i><?php echo $tr->translate('txt_menu_right_pos');?> </a></li>
                <li class="nav-header"><a href="<?php echo WEB_PATH;?>/product/backoffice"><i class="icon-Gestion"></i><?php echo $tr->translate('txt_menu_right_inventory');?> </a></li>
                <li class="nav-header"><a href="<?php echo WEB_PATH;?>/product/backoffice"><i class="icon-clients"></i><?php echo $tr->translate('txt_menu_right_debts');?> </a></li>
                <li class="nav-header"><a href="<?php echo WEB_PATH;?>/product/backoffice"><i class="icon-Employ"></i><?php echo $tr->translate('txt_menu_right_employee');?> </a></li>
                <li class="nav-header"><a href="<?php echo WEB_PATH;?>/product/backoffice"><i class="icon-ser-Clients"></i><?php echo $tr->translate('txt_menu_right_customer');?> </a></li>
                <li class="nav-header"><a href="<?php echo WEB_PATH;?>/product/marketing"><i class="icon-Carte"></i><?php echo $tr->translate('txt_menu_right_loyalty_cards');?> </a></li>
                <li class="nav-header"><a href="<?php echo WEB_PATH;?>/product/marketing"><i class="icon-Cartede"></i><?php echo $tr->translate('txt_menu_right_prepaid_cards');?> </a></li>
                <li class="nav-header"><a href="<?php echo WEB_PATH;?>/product/marketing"><i class="icon-Promotions"></i><?php echo $tr->translate('txt_menu_right_promotions');?> </a></li>
                <li class="nav-header"><a href="<?php echo WEB_PATH;?>/product/marketing"><i class="icon-Marketing"></i><?php echo $tr->translate('txt_menu_right_marketing');?> </a></li>
                <li class="nav-header"><a href="<?php echo WEB_PATH;?>/product/backoffice"><i class="icon-Chanedemagasins"></i><?php echo $tr->translate('txt_menu_right_multi_store');?> </a></li>
                <li class="nav-header"><a href="<?php echo WEB_PATH;?>/product/backoffice"><i class="icon-Rapports"></i><?php echo $tr->translate('txt_menu_right_reports');?> </a></li>
             
              </ul>

            </div><!-- class='span4' -->

        </div><!-- sanpham-->   
    </div><!-- class="row" -->
    </div><!-- container-->
<a href="<?php echo WEB_PATH;?>/front/index/home4">next</a>
<?php die(); ?>
