<?php $tr   = new Zend_Translate('ini', LANG_PATH, DEFAULT_LANGUAGE);?>
<div class='container'>
  <div class="row">

                     <div id='thongtincty'>
                     <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-giadicvu"> <?php echo $tr->translate('txt_title_map');?></div>
                      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"></div>
                      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><img src="<?php echo WEB_PATH;?>/public/front/img/thongtincty.png" class=" img-responsive bd-img"></div> <!-- class = "action-image" -->
                     
                     </div><!-- abuotus-->  
        </div><!-- class ='row' --> 
   </div><!-- container-->
<?php die();?>
