<?php $notes = $this->notes;?>
<?php $tr   = new Zend_Translate('ini', LANG_PATH, DEFAULT_LANGUAGE);?>
<div class='container ez2-tinhnang' >
	<!--
	 <div class="row">
	 	<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"></div>
	 	<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
	 		<ul>
	 			<li
	 		</ul>
	 	</div>
	 	<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"></div>
	 </div><!-- class="row" -->
	
	<div class="row height-ez2"></div>
	

	<div class="row">
		 <!-- div class='col-lg-12 col-md-12 col-sm-12 col-xs-12 tinhnang-text'>Les fonctionalités du logiciel</div -->
	 	 <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <h3 class='tinhnang-text-h3'><?php echo $notes['note8']['title'];?></h3>
          <p class='tinhnang-text-p'>
          	<?php echo $notes['note8']['description'];?>
          </p>                
         </div><!-- span 12 -->
                          
	</div><!-- class="row" -->

	  
	 	 <div class='row  '>
                   <div class="article-tinhnang">

<div class="action-layer" data-stellar-background-ratio="0.5" data-stellar-vertical-offset="100" style="background-position: 0% -46.5px;"></div>  

                              <section id="features" class="container">     
                                  <!-- Featured Section Calls to Action -->
                                <div class="row">
                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 ez-hotro-box item animate_afc d1 animate_start">
                                      
                                      <article class="ez2-block">
                                        <div class="caption-ez2"> 
                                          <h3 class='ez-txt-box-home min-height' ">
                                        
                                          <?php echo $tr->translate('txt_title_powerful');?>
                                          </h3>
                                          <ul class="nav-pills nav-stacked  nav-ul-li-home-2">
											  <li class="dis-pla-in">
											          <i class="icon-oki-home-page-eu"></i>
											          <div class="text-tx-right-home-1-home-1">   <?php echo $tr->translate('txt_title_powerful1');?></div>
											 </li>
											  <li class="dis-pla-in">
											        <i class="icon-oki-home-page-eu"></i>
											        <div class="text-tx-right-home-1-home-1">   <?php echo $tr->translate('txt_title_powerful2');?></div>
											  </li>
											  <li class="dis-pla-in">
											        <i class="icon-oki-home-page-eu"></i>
											        <div class="text-tx-right-home-1-home-1">   <?php echo $tr->translate('txt_title_powerful3');?></div>
											  </li>
											   <li class="dis-pla-in">
											          <i class="icon-oki-home-page-eu"></i>
											          <div class="text-tx-right-home-1-home-1">   <?php echo $tr->translate('txt_title_powerful4');?></div>
											  </li>
										</ul>
                                        </div>
                                      </article>
                                    </div>
                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12  ez-hotro-box item animate_afc d2 animate_start">
                                      <article class="ez2-block">
                                        <div class="caption-ez2">  
                                          <h3 class='ez-tn-txt-box-1 min-height' style="min-height: 100px;">
                                            
                                            <?php echo $tr->translate('txt_title_safe_andsecure');?>
                                            
                                          </h3>
                                          <ul class="nav-pills nav-stacked  nav-ul-li-home-2">
											  <li class="dis-pla-in">
											          <i class="icon-oki-home-page-eu"></i>
											          <div class="text-tx-right-home-1-home-1"><?php echo $tr->translate('txt_title_safe_andsecure1');?></div>
											 </li>
											  <li class="dis-pla-in">
											        <i class="icon-oki-home-page-eu"></i>
											        <div class="text-tx-right-home-1-home-1"><?php echo $tr->translate('txt_title_safe_andsecure2');?></div>
											  </li>
											  <li class="dis-pla-in">
											        <i class="icon-oki-home-page-eu"></i>
											        <div class="text-tx-right-home-1-home-1"><?php echo $tr->translate('txt_title_safe_andsecure3');?></div>
											</li>
											   <li class="dis-pla-in">
											          <i class="icon-oki-home-page-eu"></i>
											          <div class="text-tx-right-home-1-home-1"><?php echo $tr->translate('txt_title_safe_andsecure4');?></div>
											  </li>
										</ul>
                                         
                                        </div>
                                      </article>
                                    </div>
                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12  ez-hotro-box item animate_afc d3 animate_start">
                                      <article class="ez2-block">
                                        <div class="caption-ez2">  
                                          <h3 class='ez-tn-txt-box-2 min-height' style="min-height: 100px;">
                                          
                                          <?php echo $tr->translate('txt_title_cuttingedge_technology');?>
                                          
                                          </h3>
                                          <ul class="nav-pills nav-stacked  nav-ul-li-home-2">
											  <li class="dis-pla-in">
											          <i class="icon-oki-home-page-eu"></i>
											          <div class="text-tx-right-home-1-home-1"><?php echo $tr->translate('txt_title_cuttingedge_technology1');?></div>
											 </li>
											  <li class="dis-pla-in">
											        <i class="icon-oki-home-page-eu"></i>
											        <div class="text-tx-right-home-1-home-1"><?php echo $tr->translate('txt_title_cuttingedge_technology2');?></div>
											  </li>
											  <li class="dis-pla-in">
											        <i class="icon-oki-home-page-eu"></i>
											        <div class="text-tx-right-home-1-home-1"><?php echo $tr->translate('txt_title_cuttingedge_technology3');?>
											        </div>
											</li>
											   <li class="dis-pla-in">
											          <i class="icon-oki-home-page-eu"></i>
											          <div class="text-tx-right-home-1-home-1"><?php echo $tr->translate('txt_title_cuttingedge_technology4');?></div>
											  </li>
										</ul>
                                        </div>
                                      </article>
                                    </div>
                                  </div><!-- class="row" -->
                                  <!-- End Featured Section Calls to Action -->
                                </section>
                      </div><!-- class="article-tinhnang" -->
	 </div><!-- class="row" -->
</div><!-- container-->
<div class="next"><a href="<?php echo WEB_PATH;?>/front/index/home3">next</a></div>
<?php die();?>