<style>
<!-- tim kiem -->
.navbar > .container .navbar-brand {
margin: 18px 0 10px;
}

.navbar {
top: -21px;
margin-bottom: 0px !important;
z-index: 5;
}
.container>.navbar-header, .container>.navbar-collapse {
margin-right: 0;
margin-left: 0;
}
#suggestions {
position: absolute;
z-index: 100;
}
header a.logo {
background: url('<?php echo WEB_PATH?>/public/m.front/images/logo_fpt_play.png') no-repeat left center;
width: 160px;
display: block;
}
header .search {
float: right;
padding: 0 20px;
margin: 16px 0 11px;
border-right: 1px solid #d3d3d3;
width: 250px;
}
header .download {
float: right;
background: url('<?php echo WEB_PATH?>/public/m.front/images/icon_download.png') left 5px no-repeat;
padding-left: 45px;
text-transform: uppercase;
}

.input-group-btn:last-child>.btn {
margin-left: -1px;
}
header .download a.apple {
background: url('<?php echo WEB_PATH?>/public/m.front/images/icon_apple.png');
}
header .download a {
width: 50px;
height: 50px;
display: block;
float: left;
margin-top: 3px;
}
a {
color: #272727;
cursor: pointer;
}
.pull-left {
float: left !important;
margin-top: 9%;
}
header .download a.android {
background: url('<?php echo WEB_PATH?>/public/m.front/images/icon_android.png');
}
header .download a.window {
background: url('<?php echo WEB_PATH?>/public/m.front/images/icon-window.png');
}

header .download a.android:hover 	{ background:url('<?php echo WEB_PATH?>/public/m.front/images/icon_android_on.png'); }
header .download a.apple:hover 		{ background:url('<?php echo WEB_PATH?>/public/m.front/images/icon_apple_on.png');}
header .download a.window:hover 		{ background:url('<?php echo WEB_PATH?>/public/m.front/images/window-hover.png');}

</style>
<script>
$(document).ready(function()
		{
	    var url = "<?php echo WEB_PATH;?>/public/cache/<?php echo $this->namefile;?>.json";
	    var urlget ="<?php echo WEB_PATH;?>/front/index/detail/?id=" ;//detail
		$.getJSON(url, function(data)
		{  			 
		var totalCount=5;
		var jsondata='';
		$.each(data.Messages, function(i, M)
		{
		// alert(JSON.stringify(M.image_thumbnail));
		jsondata +='<li style="height: 217px;"><a href="'+urlget+M.id+'" style="height: 217px; width: 217px;"><img style="width: 217px; margin-bottom: 1px; background: url('+M.image_thumbnail+') 50% 50% / cover no-repeat scroll transparent;" src="http://p0.ttimg.vn/images/spacer.gif"><span></span></a></li>';
	     
		});
		//$(jsondata).appendTo("#promoted234");

		});
		
		
		// seacrh
				getContentdetailfull(1);
			$('#search').click(function(){
			   var keyword =  $('#keyword').val('');
			   alert(keyword);return;
				getContentdetailfull(1);
			});
			$('#reset').click(function(){
				$('#keyword').val('');
				getContentdetailfull(1);
			});
			$('#keyword').keypress(function(event){
				var keycode = (event.keyCode ? event.keyCode : event.which);
				if(keycode == '13'){
					getContentdetailfull(1); return false;
				}
		 });
		}); 

		function deletecontentdetailfull(contentdetailfullId){
			if(confirm('Bạn có chắc chắn muốn xóa dữ liệu này không? Dữ liệu sẽ bị xóa và không thể phục hồi!')){
				$('#loading').show();
				$('#'+contentdetailfullId).hide("slow");
				$.ajax({
					url: $("#contentdetailfullUrl").val(),
					cache: false,
					type: "POST",
					data: "do=delete&id="+contentdetailfullId,           
					success: function(serverData){
						$('#loading').hide();
					}
				});
			}
		}
		});
</script>
   
<script>
$(document).ready(function(){
	
</script>	




<?php 
	$notes = $this->notes;
	$tr   = new Zend_Translate('ini', LANG_PATH, DEFAULT_LANGUAGE);
	//echo $this->action('slider','elements','front');

?>

     <!--Content-->
     <div id="main">
     
      <header class="navbar bs-docs-nav">
            <div class="container">
                  <div class="navbar-header">
                	
                    <a class="navbar-brand logo" href="<?php echo WEB_PATH?>">
                    <img alt="" src="<?php echo WEB_PATH;?>/public/m.front/img/logo-tt.png" style="width: 96px;float:left;height: 35px;margin-left: 37%;margin-top: 8%;">
                    </a>
   
                  </div>
                   <div class="download">
                   		<p class="pull-left text_download_app">Tải ứng dụng</p>
                      	<a class="apple" target="_blank" href="https://play.google.com/store/apps/details?id=com.playboyviet.alatca.vn"></a>
                        <a class="android" target="_blank" href="https://play.google.com/store/apps/details?id=com.playboyviet.alatca.vn"></a>
                         <a class="window" target="_blank" href="https://play.google.com/store/apps/details?id=com.fptplay.activity"></a>
                  
                       <?php /*?> <a style=" width: 63px; margin-right: 5px; height: 63px;" class="window" target="_blank" href="https://play.google.com/store/apps/details?id=com.fptplay.activity"></a> */?>
                    </div>
                    
                    <div class="search">
                        <div class="input-group" style="display: inline-block;">
							  <input placeholder="Enter a keyword ..." title="Enter a keyword ..." type="text" size="30" value="" class="form-control" id="keyword"  style="float: left;width: 76%;"><!-- onkeypress="searchKeyPress(event);" onkeyup="suggestElasticSearch(this.value);" -->
							  <div id="suggestions" style="box-shadow: rgb(136, 136, 136) 5px 10px 10px; -webkit-box-shadow: rgb(136, 136, 136) 5px 10px 10px;"></div>
							  <span class="input-group-btn" style="float: right;height: 27px;margin-top: -3px;">
							   <button id="search" class="btn btn-default" type="button" ">
							    <i class="icon-search icon-white" style=" float: right;"></i>
							   </button><!-- onclick="elasticSearch() -->
							    </span>
								 <button style="width: 30px !important;background: none; border: 0px;">
		                             		 <i id="loading" class="icon-spinner icon-spin"></i>
		                         </button>
						 </div>
                    </div>    

            </div>
     </header>
     
     	<!-- BEGIN: Hot nen xem -->
       <div id="promoted"><div class="thumbnails">
       <h2><a href="#"><i class="icon-hottest"></i>Hot ! nên xem nhất</a>
         <ul class="clearfix">
         
           <div id="promoted234">
           <?php
//            echo "<pre>";
//            print_r($this->Promoted);
//            echo "</pre>";

            if( (is_array($this->Promoted)) and (!empty($this->Promoted) ))
           {  foreach ($this->Promoted as $key =>$valueker){
           	?>
           <li style="height: 217px;">
           <a href="<?php echo WEB_PATH;?>/front/index/detail/?id=<?php echo $valueker['id'];?>" style="height: 217px; width: 217px;">
           <img style="max-height: 108%;width: 217px; margin-bottom: 1px; background: url('<?php // echo $valueker['image_thumbnail']?>') 50% 50% / cover no-repeat scroll transparent;" src="<?php echo $valueker['image_thumbnail']?>">
           <span></span>
           </a>
           </li>
           <?php } }?>
            </div>
         </ul>
       </h2>
       </div></div>
<!-- END: hot nen xem -->

<!-- BEGIN: Photograper -->
<div class="thumbnails">
	<h2><a><i class="icon-members"></i>Nhiếp ảnh gia - nổi bật khác</a></h2>
    <ul class="clearfix" id="promotedUser">
        <script type="text/javascript">
           photo_ajax.promotedUser();
        </script> 
    </ul>
</div> 
<!-- END: Photograper -->

<!-- BEGIN: Goc ha noi -->
<!-- END: Goc Ha Noi -->

<!-- BEGIN: tam tay club -->
<!-- END: tam tay club -->

<!--large thumbnail-->
<?php 
// echo "<pre>";
// print_r($this->hotgirlsnew);
// echo "</pre>";
?>
<div id="thumbnails">
    <!--<ul id="container" class="clearfix" style="width:100%!important;">-->
        <div id="container" class="clearfix">
        <?php foreach ($this->hotgirlsnew as $keynew => $valuekeynew) {
        	if($valuekeynew['image_thumbnail']!="") { ?>
			<div class="box">
			    <a href="<?php echo WEB_PATH;?>/front/index/readviewdetail/?id=<?php echo $valuekeynew['id']; ?>" class="thumbnail">
			        <img src="<?php echo $valuekeynew['image_thumbnail'];?>" />
			    </a>
			    <div class="toolAlbum">
			        <ul class="clearfix">
			            <li style="  text-align: center; color: rgb(34,23,23);"><?php echo $valuekeynew['content_detail'];?></li>
			        </ul>
			    </div>
			    <div class="toolAlbum">
			        <ul class="clearfix">
			            <li><i class="icon-thumbs-up"></i><?php echo rand(1, 50)?></li>
			            <li><i class="icon-comment"></i><?php echo rand(1, 200)?></li>
			            <li><i class="icon-eye"></i><?php echo rand(2, 400)?></li>
			        </ul>
			    </div>
			</div>
		<?php } }// end foreach?>	

       
      </div>       <!--</ul>-->
    
</div>
<!-- <nav id="page-nav"> -->
<!-- 	<a href="home/ajax/?page=2"></a> -->
<!-- </nav>    -->
 </div>
    </div><!-- END: wrap -->
   </div><!-- END : pageG -->
   
    <!--sidebar-right--> 
    <!--
    <div class="sidebar-right">	
            <div class="sidebar-hide-scroll-right clearfix">
                            <div class="login">
              <form action="http://ids.tamtay.vn/user/login" method="post">
                      <legend></legend>
                      <span class="signin"><a href="#"></a></span>
                      <input type="text" name="username" placeholder="Tên đăng nhập"/>
                      <input type="password" name="password" placeholder="Mật khẩu"/>
                      <input type="hidden" name="ref" value="" />
                      <button type="submit" class="btn">Đăng Nhập</button>
                  </form>
              </div>
                            <div class="navTamtay">	
                    <ul>
                    	<li><a href="http://www.tamtay.vn/home" class="clearfix"><span class="img-circle"><i class="myhome"></i></span>Nhà tôi</a></li>
                        <li><a href="http://m.photo.tamtay.vn" class="clearfix"><span class="img-circle"><i class="photo"></i></span>Ảnh</a></li>
                        <li><a href="http://m.blog.tamtay.vn" class="clearfix"><span class="img-circle"><i class="blog"></i></span>Blog</a></li>
                        <li><a href="http://m.sukien.tamtay.vn" class="clearfix"><span class="img-circle"><i class="game"></i></span>Sự kiện</a></li>
                        
                    </ul>
                </div>
            </div>
    </div>
    -->
    
   