<script>
$(document).ready(function()
		{
	    var url = "<?php echo WEB_PATH;?>/public/cache/<?php echo $this->namefile;?>.json";
		$.getJSON(url, function(data)
		{  			 
		var totalCount=5;
		var jsondata='';
		$.each(data.Messages, function(i, M)
		{
		// alert(JSON.stringify(m));
		var num = Math.ceil( Math.random() * totalCount );
		var i = Math.random();
// 		jsondata +='<div class="stbody"><span class="timeline_square color'+num+'"></span><div class="stimg"><img src="'+M.src+'" /></div>'
// 		             +'<div class="sttext"><span class="stdelete" title="Delete">X</span><b>'+M.aid+'</b><br/>'+M.thumbnail
// 		             +'<div class="sttime"><img src="'+M.thumbnail+'" style="width:100%;height:auto; border-radius:1px solid white;padding:5px;" /></div><div class="stexpand">Playboy Viet</div></div></div>';

		jsondata +='<li style="height: 217px;"><a href="'+M.thumbnail+'" style="height: 217px; width: 217px;"><img style="width: 217px; margin-bottom: 1px; background: url(http://img3.tamtay.vn/'+M.thumbnail+') 50% 50% / cover no-repeat scroll transparent;" src="http://p0.ttimg.vn/images/spacer.gif"><span></span></a></li>';
	     
		});
		$(jsondata).appendTo("#promoted234");

		});
		});
</script>


   
		




<?php 
	$notes = $this->notes;
	$tr   = new Zend_Translate('ini', LANG_PATH, DEFAULT_LANGUAGE);
	//echo $this->action('slider','elements','front');

?>

     <!--Content-->
     <div id="main">
      <div>
      <script type="text/javascript" src="http://zone.sosmart.vn/sosmart.js#2188"></script>
<noscript><a href="http://zone.sosmart.vn/ck.php?n=abc2188f4&oaparams=2__zoneid=2188"  target="_blank"><img src="http://zone.sosmart.vn/avw.php?zoneid=2188&n=abc2188f4" border="0" alt="SoSmart Banner" /></a></noscript>
      </div>
     	<!-- BEGIN: Hot nen xem -->
       <div id="promoted"><div class="thumbnails">
       <h2><a href="#"><i class="icon-hottest"></i>Hot ! nên xem nhất</a>
         <ul class="clearfix">
           <div id="promoted234"> </div>
         </ul>
       </h2>
       </div></div>
<!-- END: hot nen xem -->

<!-- BEGIN: Photograper -->
<div class="thumbnails">
	<h2><a><i class="icon-members"></i>Nhiếp ảnh gia - nổi bật khác</a></h2>
    <ul class="clearfix" id="promotedUser">
        <script type="text/javascript">
           photo_ajax.promotedUser();
        </script> 
    </ul>
</div> 
<!-- END: Photograper -->

<!-- BEGIN: Goc ha noi -->
<!-- END: Goc Ha Noi -->

<!-- BEGIN: tam tay club -->
<!-- END: tam tay club -->

<!--large thumbnail-->
<div id="thumbnails">
    <!--<ul id="container" class="clearfix" style="width:100%!important;">-->
        <div id="container" class="clearfix">
<div class="box">
    <a href="<?php echo WEB_PATH;?>/public/m.front/detail.html" class="thumbnail">
        <img src="http://img3.tamtay.vn/files/photo2/2014/7/8/22/1803802/53bc1550_0a543926_95e76ff5654e19d8767892205b68a6fa_thumb.jpg" />
    </a>
    <div class="toolAlbum">
        <ul class="clearfix">
            <li><i class="icon-thumbs-up"></i>1</li>
            <li><i class="icon-comment"></i>5</li>
            <li><i class="icon-eye"></i>653</li>
        </ul>
    </div>
</div>
<div class="box">
    <a href="<?php echo WEB_PATH;?>/front/index/detail" class="thumbnail">
        <img src="http://img3.tamtay.vn/files/photo2/2014/7/11/0/8101116/53bed382_7c741121_studionguyen-1_thumb.jpg" />
    </a>
    <div class="toolAlbum">
        <ul class="clearfix">
            <li><i class="icon-thumbs-up"></i>0</li>
            <li><i class="icon-comment"></i>0</li>
            <li><i class="icon-eye"></i>394</li>
        </ul>
    </div>
</div>
<div class="box">
    <a href="/xem-anh/583884/phieu.html" class="thumbnail">
        <img src="http://img3.tamtay.vn/files/photo2/2014/7/11/14/13710262/53bf957f_4437a37b_9e55735416ce8cbc5de60e67403425b4_thumb.jpg" />
    </a>
    <div class="toolAlbum">
        <ul class="clearfix">
            <li><i class="icon-thumbs-up"></i>4</li>
            <li><i class="icon-comment"></i>0</li>
            <li><i class="icon-eye"></i>1.281</li>
        </ul>
    </div>
</div>
<div class="box">
    <a href="<?php echo WEB_PATH;?>/front/index/detail" class="thumbnail">
        <img src="http://img3.tamtay.vn/files/photo2/2014/7/12/13/14159719/53c0d685_6adee894_91bb82ed9108bdc9c013f22f5c980ef6_thumb.jpg" />
    </a>
    <div class="toolAlbum">
        <ul class="clearfix">
            <li><i class="icon-thumbs-up"></i>0</li>
            <li><i class="icon-comment"></i>0</li>
            <li><i class="icon-eye"></i>541</li>
        </ul>
    </div>
</div>
<div class="box">
    <a href="/xem-anh/583810/co-em-o-day.html" class="thumbnail">
        <img src="http://img3.tamtay.vn/files/photo2/2014/7/12/10/8866240/53c0af6c_410a87b7_42640ef6b9147cafc579fd2afd673ede_thumb.jpg" />
    </a>
    <div class="toolAlbum">
        <ul class="clearfix">
            <li><i class="icon-thumbs-up"></i>0</li>
            <li><i class="icon-comment"></i>0</li>
            <li><i class="icon-eye"></i>177</li>
        </ul>
    </div>
</div>
<div class="box">
    <a href="/xem-anh/583760/hot-girl-nha-trang.html" class="thumbnail">
        <img src="http://img3.tamtay.vn/files/photo2/2014/7/10/21/13710262/53be9f75_225d05e0_852101bdf67c67753631d1021ba3919a_thumb.jpg" />
    </a>
    <div class="toolAlbum">
        <ul class="clearfix">
            <li><i class="icon-thumbs-up"></i>2</li>
            <li><i class="icon-comment"></i>2</li>
            <li><i class="icon-eye"></i>2.791</li>
        </ul>
    </div>
</div>
<div class="box">
    <a href="/xem-anh/583759/toc-roi.html" class="thumbnail">
        <img src="http://img3.tamtay.vn/files/photo2/2014/7/8/21/11937131/53bc04e8_0ceb71b3__dsc0264_thumb.jpg" />
    </a>
    <div class="toolAlbum">
        <ul class="clearfix">
            <li><i class="icon-thumbs-up"></i>0</li>
            <li><i class="icon-comment"></i>2</li>
            <li><i class="icon-eye"></i>1.359</li>
        </ul>
    </div>
</div>
<div class="box">
    <a href="/xem-anh/583876/girl-linh-chien.html" class="thumbnail">
        <img src="http://img3.tamtay.vn/files/photo2/2014/7/11/20/1803802/53bfe8d1_2985944c_cab193de5ade5f5ad8fb822ce574f883_thumb.jpg" />
    </a>
    <div class="toolAlbum">
        <ul class="clearfix">
            <li><i class="icon-thumbs-up"></i>2</li>
            <li><i class="icon-comment"></i>2</li>
            <li><i class="icon-eye"></i>791</li>
        </ul>
    </div>
</div>
<div class="box">
    <a href="/xem-anh/583871/mau-nang.html" class="thumbnail">
        <img src="http://img3.tamtay.vn/files/photo2/2014/7/10/22/12128865/53beb7b3_2b0cd14a_57d8106c4f6f24e4d109e87e2a519dd1_thumb.jpg" />
    </a>
    <div class="toolAlbum">
        <ul class="clearfix">
            <li><i class="icon-thumbs-up"></i>5</li>
            <li><i class="icon-comment"></i>4</li>
            <li><i class="icon-eye"></i>970</li>
        </ul>
    </div>
</div>
<div class="box">
    <a href="detail.html" class="thumbnail">
        <img src="http://img3.tamtay.vn/files/photo2/2014/7/11/21/362893/53bff8db_111d8ae6_14362216800_94f944fc33_o_thumb.jpg" />
    </a>
    <div class="toolAlbum">
        <ul class="clearfix">
            <li><i class="icon-thumbs-up"></i>6</li>
            <li><i class="icon-comment"></i>1</li>
            <li><i class="icon-eye"></i>1.667</li>
        </ul>
    </div>
</div>
       
</div>       <!--</ul>-->
    
</div>
<nav id="page-nav">
	<a href="home/ajax/?page=2"></a>
</nav>    </div>
    </div><!-- END: wrap -->
   </div><!-- END : pageG -->
   
    <!--sidebar-right--> 
    <!--
    <div class="sidebar-right">	
            <div class="sidebar-hide-scroll-right clearfix">
                            <div class="login">
              <form action="http://ids.tamtay.vn/user/login" method="post">
                      <legend></legend>
                      <span class="signin"><a href="#"></a></span>
                      <input type="text" name="username" placeholder="Tên đăng nhập"/>
                      <input type="password" name="password" placeholder="Mật khẩu"/>
                      <input type="hidden" name="ref" value="http%3A%2F%2Fm.photo.tamtay.vn" />
                      <button type="submit" class="btn">Đăng Nhập</button>
                  </form>
              </div>
                            <div class="navTamtay">	
                    <ul>
                    	<li><a href="http://www.tamtay.vn/home" class="clearfix"><span class="img-circle"><i class="myhome"></i></span>Nhà tôi</a></li>
                        <li><a href="http://m.photo.tamtay.vn" class="clearfix"><span class="img-circle"><i class="photo"></i></span>Ảnh</a></li>
                        <li><a href="http://m.blog.tamtay.vn" class="clearfix"><span class="img-circle"><i class="blog"></i></span>Blog</a></li>
                        <li><a href="http://m.sukien.tamtay.vn" class="clearfix"><span class="img-circle"><i class="game"></i></span>Sự kiện</a></li>
                        
                    </ul>
                </div>
            </div>
    </div>
    -->
    
   