<form id="frmList" name="frmList" method="post">
<input type="hidden" id="UrlUrl" value="<?php echo WEB_PATH;?>/administrator/contentdetailfull" />
	<br/>
	<div class="row">
	<?php 
	$message="";
	
	if(isset($_GET['status'])){
	$status	  = $_GET['status'];
	}else{
		$status="";
	}
	//echo $status;
	if($status == 1){
		$stt="Update";
		$message = '<div class="alert alert-success alert-dismissable">
                <a class="close" data-dismiss="aler" href="#">&times;</a>
					<i class="icon-ok-sign"></i>
                <strong>'.$stt.'</strong>
                Success !

              </div>';
	}
	if($status == 2){
		$stt="Add new";
		$message = '<div class="alert alert-success alert-dismissable">
                <a class="close" data-dismiss="aler" href="#">&times;</a>
					<i class="icon-ok-sign"></i>
                <strong>'.$stt.'</strong>
                 Success !
	
              </div>';
	}
	?>
	<div class="box_message"><?php echo $message; ?></div>
	<div class="col-md-4">
	 <div class=' page-header-with-buttons'>
	 	
                <h1 class='' style="margin-top: 0px;">
                  <i class=' icon-paper-clip  '></i>
                  <span class="page_title">Hot girl management</span>
                </h1>
              	</div>
	</div>                  
       		<div class="col-md-2 pull-right ">
         			
 <!--               		 <a href="<?php echo WEB_PATH;?>/administrator/contentdetailfull/update" class="btn btn-primary pull-right" title="Add"> <i class="icon-plus "></i> 
              		Add 
              		 </a>
      -->
              		
            </div>   
            <div class="col-md-5 pull-right">
			<div class="input-group controls-group">
			
		                              <input id="keyword" name="keyword" class="form-control" type="text" name="q" class="form-control pull-left" placeholder="Enter a keyword ..." title="Enter a keyword ..." value="">
		                              
		                              <span class="input-group-btn">
		                                <button id="search" type="button" class="btn  btn-primary" title="Search">
		                                  <i class="icon-search"></i>
		                                </button>
		                                <?php echo $this->contentdetailfullGroup; 
	                                        // $bien = $this->ContentdetailfullGroup; var_dump($bien);?>
		                                  <button  id="reset" type="button" class="btn btn-primary" title="Reset">
		                                  <i class="icon-refresh"></i>
		                                </button>
		                                
		                                <button style="width: 30px !important;background: none; border: 0px;">
		                             		 <i id="loading" class="icon-spinner icon-spin"></i>
		                                </button>
		                              </span>
		                            </div>
		       </div>
	</div>
	<span id="contentdetailfullArea"></span>

</form>
<?php /* ?>
<a class='btn btn-info btn-lg' data-toggle='modal' href='#modal-addnew' role='button'>Launch modal with form</a>
*/?>

<div class='modal fade' id='modal-addnew' tabindex='-1'>
                      <div class='modal-dialog'>
                        <div class='modal-content'>
                          <div class='modal-header'>
                            <button aria-hidden='true' class='close' data-dismiss='modal' type='button'>×</button>
                            <h4 class='modal-title' id='myModalLabel'>Modal with form</h4>
                          </div>
                          <div class='modal-body'>
                                          <form class="form" style="margin-bottom: 0;" method="post" action="#" accept-charset="UTF-8"><input name="authenticity_token" type="hidden" /><div class='form-group'>
                              <label for='inputText1'>Text field</label>
                              <input class='form-control' id='inputText1' placeholder='Text field' type='text'>
                            </div>
                            <div class='form-group'>
                              <label for='inputPassword4'>Password field</label>
                              <input class='form-control' id='inputPassword4' placeholder='Password field' type='password' value='Top secret!'>
                            </div>
                            <div class='form-group'>
                              <label for='inputTextArea1'>Textarea</label>
                              <textarea class='form-control' id='inputTextArea1' placeholder='Textarea' rows='3'></textarea>
                            </div>
                            <div class='form-group'>
                              <label for='disabledInput1'>Disabled input</label>
                              <input class='form-control' disabled='' id='disabledInput1' placeholder='Disabled input here...' type='text'>
                            </div>
                            <hr class='hr-normal'>
                            <div class='form-group'>
                              <label>Checkboxes</label>
                              <div class='checkbox'>
                                <label>
                                  <input type='checkbox' value=''>
                                  autem quas sint ut ab
                                </label>
                              </div>
                              <div class='checkbox'>
                                <label>
                                  <input type='checkbox' value=''>
                                  expedita delectus odit modi optio
                                </label>
                              </div>
                              <div class='checkbox'>
                                <label>
                                  <input type='checkbox' value=''>
                                  qui est
                                </label>
                              </div>
                            </div>
                            </form>
              
                          </div>
                          <div class='modal-footer'>
                            <button class='btn btn-default' data-dismiss='modal' type='button'>Close</button>
                            <button class='btn btn-primary' type='button'>Save changes</button>
                          </div>
                        </div>
                      </div>
                    </div>


