<?php 
    $objUtil = new HT_Model_administrator_models_utility();
	$contentdetailfull = $this->contentdetailfull;
	$status	  = $this->status;
	$message  = null;
	if($status == 1){
		$message = '<div class="ub_message">The data has been updated</div>';
	}elseif($status == "-1"){
		$message = '<div class="ub_message"><span>Note key is already exists! Please choice other key.</span></div>';
	}
	$active = (int)@$contentdetailfull['active'];

?>
<div class='row' id='content-wrapper'>
            <div class='col-xs-12'>
              <div class='row'>
                <div class='col-sm-12'>
                  <div class='page-header'>
                    <h1 class='pull-left'>
                      <i class='icon-edit'></i>
                      <span class="page_title"><?php if($this->id > 0) echo "Update a contentdetailfull"; else echo "Add a contentdetailfull"?></span>
                    </h1>
                  </div>
                </div>
              </div>
              <div class='row'>
                <div class='col-sm-12'>
                  <div class='box'>
                    <div class='box-header blue-background'>
                      <div class='title'>
                        <div class='icon-edit'></div>
                        Add / Edit
                      </div>
                      <div class='actions'>
                        <a class="btn box-remove btn-xs btn-link" href="#"><i class='icon-remove'></i>
                        </a>
                        <a class="btn box-collapse btn-xs btn-link" href="#"><i></i>
                        </a>
                      </div>
                    </div>
                    <div class='box-content'>
                        <form id="frmUpdate" name="frmUpdate" class="form form-horizontal" style="margin-bottom: 0;" method="post" action="<?php echo WEB_PATH;?>/administrator/contentdetailfull/update" enctype="multipart/form-data" accept-charset="UTF-8">
						<input type="hidden" id="id" name="id" value="<?php echo $this->id;?>">
						<input type="hidden" id="do" name="do" value="submit" />
                        <input name="idforeign" type="hidden" id="idforeign" value="<?php echo $this->idforeign;?>"/>
                      <div class='form-group'>
                        <label class='col-md-3 control-label' for='contentdetailfull_key'>Title - NameApp</label>
                        <div class='col-md-9'>
                        	<?php echo $this->contentdetailfullGroup; 
                        	       //var_dump($this->contentdetailfullGroup);
                        	       //print_r($this->contentdetailfullGroup);
                        	       ?>
                        </div>
                      </div>
                     <?php 
                      $http   = 'http';
                    //  var_dump((strpos($contentdetailfull['src'],$http )));
                      ?>
                  <?php if( ((strpos($contentdetailfull['src'],$http )=== 0) ) and ($contentdetailfull['src'] !='')) {?>
                      <div class='form-group'>
                        <label class='col-md-3 control-label' for='thumbnail'>ThumbNail</label>
                        <div class='col-md-9'>
                           <img type="text" class='form-control' id="thumbnail" name="thumbnail" placeholder='Images' src="<?php echo @$contentdetailfull['src'];?>" style="width: 400px;height:400px;" />
                        </div>
                      </div>
                   <?php }
                   if( ( (strpos($contentdetailfull['src'],$http )=== false) and ($contentdetailfull['src'] !='') ) )  {?>
                      <div class='form-group'>
                        <label class='col-md-3 control-label' for='thumbnail'>ThumbNail</label>
                        <div class='col-md-9'>
                           <img type="text" class='form-control' id="thumbnail" name="thumbnail" placeholder='Images' src="<?php echo WEB_PATH;?>/public/uploads/news/<?php echo @$contentdetailfull['src'];?>" style="width: 400px;height:400px;" />
                        </div>
                      </div>
                   <?php }?> 
                   
                      <?php if($image){?>
                        <div class='form-group'>
                          <label class='control-label col-sm-3' for='Thứ tự sắp xếp ưu tiên'>Ảnh đang dùng</label>
                          <div class='col-sm-4 controls'>
                            <img width="340" height="230" alt="<?php echo @$contentdetailfull['src'];?>" src="<?php echo WEB_PATH;?>/public/uploads/news/<?php echo $image;?>" />
			              <input type="checkbox" name="delete_image"> Xóa ảnh 
                           </div>
                        </div>
                        <?php }?>
                        
                      <div class='form-group'>
                        <label class='col-md-3 control-label' for='srcimgaes'>Images</label>
                        <div class='col-md-9'>
                        	<input class='form-control' id='srcimgaes' name='srcimgaes' type="file" />
                        </div>
                      </div>
                      
                    <?php /*?> 
                      <div class='form-group'>
                        <label class='col-md-3 control-label' for='title' placeholder='Page URL'>title</label>
                        <div class='col-md-9'>
                        	<input  class='form-control' type="text" id="title" name="title" value="<?php echo @$contentdetailfull['contentdetailfull_title'];?>" />
                        </div>
                      </div>
                       <div class='form-group'>
                          <label class='control-label col-sm-3' for=''> Description</label>
                       </div>
                       <div class='form-group' style = " margin: 0px 20px 0px 20px ; " >
                           <textarea type="text" id="description" name="description"><?php echo stripcslashes(@$contentdetailfull['description']);?></textarea>
                           <?php $objUtil->renderCkeditor('description',400)?>
                       </div>
                      */?> 
                       
                      <div class='form-actions form-actions-padding-sm'>
                        <div class='row'>
                          <div class='col-md-9 col-md-offset-3'>
                            <button class='btn btn-primary' onclick="return validateData()" >
                              <i class='icon-save'></i>
                              Save
                            </button>
                            <a href="<?php echo WEB_PATH.'/administrator/contentdetailfull';?>"><div class='btn'>Cancel</div></a>
                          </div>
                        </div>
                      </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
</div>